### ISSUE TITLE
My app refuses to open with start button

### ISSUE THREAD

**Issue by BermyToiga** [atsign-foundation/at_widgets#1]
I've added all the dependencies and started moving a bit of code over to get this working in my app, however when I try to add this code: 
`Center(child: StartButton(nextScreen: SecondScreen())),`
To my app's sign in screen, it will not open, without any reason in output

Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Xcode build done.                                           16.7s
Connecting to VM Service at ws://127.0.0.1:59244/sUqI-ad52vQ=/ws
Lost connection to device.
Exited (sigterm)

**Comment by sarika01** [comment]
Were you able to run the example app?

**Comment by BermyToiga** [comment]
Yes the example app runs fine

**Comment by sarika01** [comment]
@BermyToiga The plugin has been modified to have only the authentication flow. Can you please try again?

**Comment by BermyToiga** [comment]
Seems to work now, thanks!
