### ISSUE TITLE
test and release namespace changes in widgets.

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_widgets#105]

**Comment by murali-shris** [comment]
https://docs.google.com/presentation/d/1xpZMHa6fgri9YXMmeHYulp-4t_hoPhr-t_dTkv14sQ8/edit#slide=id.p
https://docs.google.com/document/d/1qG7BXFrrtTrwr8YWTKIOKmeELk5xk2yzclNDjPWZJHU/edit

**Comment by sarika01** [comment]
These changes have been implemented in at_contacts_flutter, at_contacts_group_flutter, at_chat_flutter, at_events_flutter and at_location_flutter.
These libraries do not use name of their own. The client preferences (namespace) are picked from the parent app.

**Comment by purnimavenkatasubbu** [comment]
Testing Notes:

- [x] **at_follows_flutter :**

1. Installed the current version of the play store app and added some atsigns to the following and followers list(Both following and followers list as public)
2. Checked the key format by connecting to the terminal
at_followers_of_self.wavi@ bluegreen129slow","at_following_by_self.wavi@ bluegreen129slow"
3. Now changed the pubspec.yaml to point to the "namespace_changes_without_sdkrefactoring branch" of at_follows_flutter and installed.
4. Checked the keys from the terminal.
scan
data:["followers_of_self.at_follows.wavi@ bluegreen129slow","following_by_self.at_follows.wavi@ bluegreen129slow","image.wavi@ bluegreen129slow","lastname.wavi@ bluegreen129slow","location.wavi@ bluegreen129slow","locationnickname.wavi@ bluegreen129slow","phone.wavi@ bluegreen129slow","publickey@ bluegreen129slow","signing_publickey@ bluegreen129slow"]

**Scenario -2 (Followers list as private and Following list as public)**

**Keys before migration**
"public:at_following_by_self.wavi@ 94zeher3ultimate", "@94zeher3ultimate:at_followers_of_self.wavi@ 94zeher3ultimate"

**Keys after migration**
followers_of_self.at_follows.wavi@ 94zeher3ultimate","profilepic.buzz@ 94zeher3ultimate","public:about.wavi@ 94zeher3ultimate","public:custom_youtubeurl.wavi@ 94zeher3ultimate","public:discord.wavi@ 94zeher3ultimate","public:email.wavi@ 94zeher3ultimate","public:firstname.wavi@ 94zeher3ultimate","public:following_by_self.at_follows.wavi@ 94zeher3ultimate"


- [x] **at_contact library with at_buzz app**

1) Installed the latest version of at_buzz pointing to trunk branch of at_contact
2) Created connections made them favorites, added nicknames, and notes
3) Checked the key format from the terminal
atconnections.37quiet.contacts.munich15creative@ munich15creative","atconnections.94zeher3ultimate.contacts.munich15creative@ munich15creative","atconnections.judicialabseiling.contacts.munich15creative@ munich15creative"
4) Installed the app pointing to the namespace_changes branch of at_contact	
atconnections.37quiet.munich15creative.at_contact.buzz@ munich15creative","atconnections.94zeher3ultimate.munich15creative.at_contact.buzz@ munich15creative","atconnections.judicialabseiling.munich15creative.at_contact.buzz@ munich15creative

- [x] **at_contact library to verify groups**

1. Installed at_contacts_group_flutter example app point to trunk branch of at_contact
2. Added contacts, created group, and added group picture
3. Checked the key format from the terminal

atconnections.27salty.contacts.94zeher3ultimate@ 94zeher3ultimate","atconnections.37quiet.contacts.94zeher3ultimate@ 94zeher3ultimate","atconnections.becooltasteless.contacts.94zeher3ultimate@ 94zeher3ultimate","atconnections.bluegreen129slow.contacts.94zeher3ultimate@ 94zeher3ultimate","atconnections.groupslist.94zeher3ultimate@ 94zeher3ultimate","atconnections.judicialabseiling.contacts.94zeher3ultimate@ 94zeher3ultimate","atconnections.munich15creative.contacts.94zeher3ultimate@ 94zeher3ultimate","atconnections.postpunkordinary.contacts.94zeher3ultimate@ 94zeher3ultimate"

4. Install the at_contact_group_flutter pointing to the namespace_changes branch of at_contact.
5. Check the keys from the terminal.

"atconnections.27salty.94zeher3ultimate.at_contact@ 94zeher3ultimate","atconnections.37quiet.94zeher3ultimate.at_contact@ 94zeher3ultimate","atconnections.becooltasteless.94zeher3ultimate.at_contact@ 94zeher3ultimate","atconnections.bluegreen129slow.94zeher3ultimate.at_contact@ 94zeher3ultimate","atconnections.bluegreen129slow.contacts.94zeher3ultimate@ 94zeher3ultimate","atconnections.groupslist.94zeher3ultimate.at_contact@ 94zeher3ultimate","atconnections.judicialabseiling.94zeher3ultimate.at_contact@ 94zeher3ultimate","atconnections.munich15creative.94zeher3ultimate.at_contact@ 94zeher3ultimate","atconnections.postpunkordinary.94zeher3ultimate.at_contact@ 94zeher3ultimate",

Null check operator issue in the console.

Please paste the error logs
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<String>'
E/flutter (13253): #0 AtLookupImpl.executeVerb
package:at_lookup/src/at_lookup_impl.dart:331
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #1 RemoteSecondary.executeVerb
package:at_client/…/client/remote_secondary.dart:36
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #2 SyncUtil.getLatestServerCommitId
package:at_client/…/util/sync_util.dart:83
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #3 SyncManager._sync
package:at_client/…/manager/sync_manager.dart:90
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #4 SyncManager.sync
package:at_client/…/manager/sync_manager.dart:70
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #5 LocalSecondary.executeVerb
package:at_client/…/client/local_secondary.dart:50
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #6 AtClientImpl._put
package:at_client/…/client/at_client_impl.dart:574
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #7 AtContactsImpl.get
package:at_contact/src/at_contacts_impl.dart:89
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #8 AtContactsImpl.listContacts
package:at_contact/src/at_contacts_impl.dart:160
E/flutter (13253): <asynchronous suspension>
E/flutter (13253): #9 GroupService.init
package:at_contacts_group_flutter/services/group_service.dart:78
E/flutter (13253): <asynchronous suspension>

![Screenshot from 2021-08-03 12-00-06](https://user-images.githubusercontent.com/43639593/128325504-7b745443-f965-44a5-98c5-f582801137f9.png)
![Screenshot from 2021-08-03 12-00-20](https://user-images.githubusercontent.com/43639593/128325518-89f0df29-027b-46ed-b723-a95e65cb98f0.png)
![Screenshot from 2021-08-03 12-01-13](https://user-images.githubusercontent.com/43639593/128325525-db4bcf1f-fec0-42bd-9cde-e6b93dfe0b2b.png)
![Screenshot from 2021-08-03 12-01-17](https://user-images.githubusercontent.com/43639593/128325537-7693a429-5fda-464b-a6ab-5f4af752a136.png)
![Screenshot from 2021-08-03 12-01-21](https://user-images.githubusercontent.com/43639593/128325547-b0105f80-227a-48a7-b732-6ee6a8713461.png)

**Comment by murali-shris** [comment]
at_follows_flutter 2.0.3 published

**Comment by buzz** [comment]
Please stop mentioning me in this issue. Thank you very much
