### ISSUE TITLE
Chat widget - add delete functionality

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_widgets#108]
The existing chat widget library does not support delete functionality. A partial implementation to delete all messages is done in https://github.com/atsign-foundation/at_widgets/tree/feat/chat-delete
There is a need to improve it further to be able to delete individual messages.

**Comment by sarika01** [comment]
Delete functionality is added but doesn't work with handling images. Needs some more work.

**Comment by ksanty** [comment]
@sarika01 is this the one we need to tag Gafei on?

**Comment by sarika01** [comment]
Yes @ksanty

**Comment by sarika01** [comment]
Latest version (3.0.1) published on pub.dev reflect the changes.
