### ISSUE TITLE
Chat widget - add support for images and emoticons

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_widgets#109]
The existing chat package only supports text messages. This is an enhancement to make the widget support images and emoticons.

**Comment by sarika01** [comment]
This is done. Needs publishing.

**Comment by ksanty** [comment]
@sarika01 is this the one we need to tag Gafei on?

**Comment by sarika01** [comment]
Latest version (3.0.1) published on pub.dev reflect the changes.
