### ISSUE TITLE
Not able to authenticate in at_contacts_flutter example

### ISSUE THREAD

**Issue by BermyToiga** [atsign-foundation/at_widgets#11]
I get this error when trying to scan QR code to authenticate into the example:

flutter: NoSuchMethodError: The setter 'cramSecret=' was called on null.
Receiver: null
Tried calling: cramSecret="ikpnBQu2SAQsgxNb6mLoGQrVGK4GrUB2wjWLGzHisojHUtm27-tv4knY8KgPeoUZGxXQVofFoLoltqkQbYnzJeLI6864jMxJyjEKc82DYtvQextapZUZVjliZRTaNsbS6Vd8bYqE7iEEDEHcj60hV5"

**Comment by Sameeraja-Bharathula** [comment]
atClientPreference has to be passed for atsign_authentication_helper plugin. Could you please try with passing atClientPrefernce to the plugin once!

**Comment by BermyToiga** [comment]
Hi, I have tried this and it failed with this response:

flutter: initializing storage
flutter: INFO|2021-02-18 11:23:52.843900|AtClientImpl|AtClient init  done for : @egCovidLab🛠
flutter: INFO|2021-02-18 11:23:53.221686|AtLookup|from result:data:_c3e65acd-b799-406b-aa97-c8fec6127e13@egcovidlab🛠:d3ebb03c-03f2-4582-b5e2-97804c23d4dc
flutter: INFO|2021-02-18 11:23:53.245994|AtLookup|auth success
flutter: [{id: 3, name: lastCommitID, value: 3}]
flutter: INFO|2021-02-18 11:23:53.528382|AtLookup|from result:data:_c3e65acd-b799-406b-aa97-c8fec6127e13@egcovidlab🛠:9ba8507f-6e36-43f7-b6d9-4e7aa94ea2a7
flutter: INFO|2021-02-18 11:23:53.542863|AtLookup|auth success
flutter: INFO|2021-02-18 11:23:55.110893|AtLookup|auth success
flutter: atsignMap is {}
flutter: [{id: 3, name: lastCommitID, value: 3}]
flutter: INFO|2021-02-18 11:23:56.368061|SyncManager|server and local is in sync
flutter: error in authenticating =>  'package:at_client/src/client/local_secondary.dart': Failed assertion: line 301 pos 12: 'value != null && value != ''': is not true.
flutter: 'package:at_client/src/client/local_secondary.dart': Failed assertion: line 301 pos 12: 'value != null && value != ''': is not true.

**Comment by BermyToiga** [comment]
In pubspec.yaml I changed the authentication helper dependency to ^0.0.3
In constants I changed local server to 'vip.ve.atsign.zone'
In main.dart I added atClientPreference: clientSdkService.atClientPreference, to ScanQrScreen() call

**Comment by sarika01** [comment]
The atsign_authentication_helper package is replaced with at_onboarding_flutter package in the example app.

**Comment by murali-shris** [comment]
@BermyToiga are you still facing this issue using at_onboarding_flutter ?

**Comment by BermyToiga** [comment]
I believe I am still facing this problem, I will double check one moment

**Comment by BermyToiga** [comment]
Okay, looks like this error is redundant now as authentication_helper is no longer used. I haven't tried authenticating into the at_contacts_flutter example app since it was changed to use at_onboarding_flutter, but this is okay as I just haven't needed to.

**Comment by murali-shris** [comment]
@BermyToiga can this issue be closed ?

**Comment by BermyToiga** [comment]
I think so yes, will close it now.
