### ISSUE TITLE
Duplicate keys are being created after namespace migration in follows widget

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_widgets#110]
**Describe the bug**
After migrating to the new namespace code. Instead of updating the old key, Duplicate new key is being created.

**To Reproduce**
1. First I installed the latest playstore version of wavi app
2. Then I added atsigns to the following list and followers list
3. And then checked the keys from the terminal
data:["at_followers_of_self.wavi@ helplessfuchsia","at_following_by_self.wavi@ helplessfuchsia
4. Installed the wavi app by pointing to the namespace-changes branch of the at_follows package
5.  Checked the keys from the terminal

"public:at_followers_of_self.wavi@ helplessfuchsia",
"public:at_following_by_self.wavi@ helplessfuchsia",
"public:followers_of_self.at_follows@ helplessfuchsia",
"public:following_by_self.at_follows.wavi@ helplessfuchsia",
"public:following_by_self.at_follows@ helplessfuchsia"

**Expected behavior**
Old key should be migrated to the new key format. .at_follows.wavi

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - @ wavi

**Additional context**
Branch- 
at_settings- trunk
at_follows - namespace-changes

**Comment by DivyaYadavareddy** [comment]
The issue was because of the sdk refactoring changes being included along with the namespace changes. I have created a separate branch with only namespace changes compatible to trunk.Now the issue is fixed.

**Comment by purnimavenkatasubbu** [comment]
Tested the bug fix in the branch "namespace_changes_without_sdkrefactoring". Now the old key is being migrated to the new key format as expected.

**Testing Notes:**

1.  Installed the current version of the play store app and added some atsigns to the following and followers list(Both following and followers list as public)
2.  Checked the key format by connecting to the terminal

at_followers_of_self.wavi@ bluegreen129slow","at_following_by_self.wavi@ bluegreen129slow"
3. Now changed the pubspec.yaml to point to the "namespace_changes_without_sdkrefactoring branch" of at_follows_flutter and installed.
4.  Checked the keys from the terminal.
scan
data:["followers_of_self.at_follows.wavi@ bluegreen129slow","following_by_self.at_follows.wavi@ bluegreen129slow","image.wavi@ bluegreen129slow","lastname.wavi@ bluegreen129slow","location.wavi@ bluegreen129slow","locationnickname.wavi@ bluegreen129slow","phone.wavi@ bluegreen129slow","publickey@ bluegreen129slow","signing_publickey@ bluegreen129slow"]


Scenario -2 (Followers list as private and Following list as public)

**Keys before migration**
"public:at_following_by_self.wavi@ 94zeher3ultimate", "@94zeher3ultimate:at_followers_of_self.wavi@ 94zeher3ultimate"

**Keys after migration**

followers_of_self.at_follows.wavi@ 94zeher3ultimate","profilepic.buzz@ 94zeher3ultimate","public:about.wavi@ 94zeher3ultimate","public:custom_youtubeurl.wavi@ 94zeher3ultimate","public:discord.wavi@ 94zeher3ultimate","public:email.wavi@ 94zeher3ultimate","public:firstname.wavi@ 94zeher3ultimate","public:following_by_self.at_follows.wavi@ 94zeher3ultimate"
