### ISSUE TITLE
Add a space after @sign

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_widgets#111]

**Comment by athandle** [comment]
![image](https://user-images.githubusercontent.com/61007675/127515589-c65ce01c-752b-40a8-9107-4d6bdea4773c.png)

**Comment by DivyaYadavareddy** [comment]
This issue is fixed now but we will release it in next build. below attached screenshot
![Simulator Screen Shot - iPhone 8 Plus - 2021-07-30 at 10 58 54](https://user-images.githubusercontent.com/60208911/127631721-660fa0c3-71a7-4626-a680-3ee0c06d924b.png)

**Comment by tinashe404** [comment]
fixed
