### ISSUE TITLE
Update Readme - at_location_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#123]
Review [at_location_flutter](https://pub.dev/packages/at_location_flutter) readme package version (example the package version is 2.0.3, but the readme description says - dependencies: at_lookup: ^1.0.0)

- [x] Action: remove this section from README and maybe add any other relevant information. We can remove the entire Installation section from README.

**Comment by sarika01** [comment]
The change is done. It will reflect in the next version of the package on pub.dev when published.

**Comment by sarika01** [comment]
Change is reflecting in the latest published version.
