### ISSUE TITLE
Update Readme - at_chat_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#124]
Review [at_chat_flutter ](https://pub.dev/packages/at_chat_flutter)readme package version (example the package version is 2.0.3, but the readme description says - dependencies: at_lookup: ^1.0.0)

- [x] Action: remove this section from README and maybe add any other relevant information. We can remove the entire Installation section from README.

**Comment by sarika01** [comment]
This change is not required as the version information is not present in the README.
