### ISSUE TITLE
Followers list gets updated only after restarting the app

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_widgets#128]
**Describe the bug**
Whenever an atsign follows my atsign, I get the notification immediately but the followers list gets updated only after I restart the app.

**To Reproduce**
1. First I Logged in to the wavi app as atsign A and atsignB
2. Then I Followed atsign A from atsign B
3. And then I received the notification in atsign A

**Expected behavior**
Followers list should be updated automatically

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS:  Android
 
**Were you using an @‎application when the bug was found?**
  -  @ wavi

**Additional context**
  at_follows_flutter -  namespace_changes

**Comment by DivyaYadavareddy** [comment]
fixed this issue in at_follows_flutter - namespace_changes.Attached screen recording of wavi

https://user-images.githubusercontent.com/60208911/128462151-6179ec73-301b-4e0a-8e3b-bade0f69e3a1.mp4

**Comment by purnimavenkatasubbu** [comment]
Now the followers list gets updated automatically.
