### ISSUE TITLE
Add QRCode activation of @sign back into the at_onboarding_flutter widget

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_widgets#138]
We lost the ability to scan a QRCode in the widget which means Wavi/Other apps cannot be activated..

- [x] Add functionality to Widget
- [x] Test Widget
- [x] Add to apps
- [x] wavi
- [ ] buzz
- [ ] @ mosphere's
- [x] ChitChat
- [ ] Others ?

**Comment by DivyaYadavareddy** [comment]
Added QR code scanning feature in the onboarding widget and and @purnima tested it. After testing, we released it in pub.dev with version at_onboarding_flutter: ^2.1.3  and added it to wavi and published wavi to play store with version(0.15.2+38) and App Store with version(1.3.2)
