### ISSUE TITLE
Invalid Type Cast in at_onboarding_flutter 

### ISSUE THREAD

**Issue by JasperDanC** [atsign-foundation/at_widgets#139]
**Describe the bug**
Invalid Type cast occurs on line 101 of pair_atsign.dart 
https://github.com/atsign-foundation/at_widgets/blob/44c5fd80f36822ea1a99d3dfbf794654676daab9/at_onboarding_flutter/lib/screens/pair_atsign.dart#L101

When this line is reached an exception is hit and there is no exception handling for an invalid type cast so then 
nothing happens and the app is stuck on a blank screen.

**To Reproduce**
1. Sign into onboarding with a new non-activated atsign  
2. Enter verification code sent to the email associated with the atsign
3. Hit 'Verify & Login' 

Then the blank screen appears 

**Expected behavior**
The app validates the code and asks the user to save the backup key

**Screenshots**
I did fix this issue on my project locally by changing these lines in pair_atsign.dart at 
https://github.com/atsign-foundation/at_widgets/blob/44c5fd80f36822ea1a99d3dfbf794654676daab9/at_onboarding_flutter/lib/screens/pair_atsign.dart#L101

from: 
![fixedOnoboardingCodePreFixed](https://user-images.githubusercontent.com/72470370/128945738-06c5f8e0-f2e6-412c-aca5-d92fa86522d2.PNG)

to:
![fixedOnoboardingCode](https://user-images.githubusercontent.com/72470370/128945742-5599256d-1025-48c9-9752-62c7a762befb.PNG)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 Emulator with Android API 30 
 - OS: Android 11 

Issue was found on other physical devices as well 

**Were you using an @‎application when the bug was found?**
  - @Vento

**Comment by yahu1031** [comment]
@JasperDanC yes, we have a lot more unwanted Type Casting, please wait till the new stable version gets released or add the git URL as a dependency.

**Comment by yahu1031** [comment]
Fixed with #178
