### ISSUE TITLE
Onboarding widget - No way to leave the OTP screen

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#157]
**Describe the bug**
If you are activating an atsign using the onboarding widget, when you go to the verification screen there is no way to leave this screen and go back to the previous one. Someone might want to do this if the verification code didn't get sent or if they change their mind on which atsign to use.  

**To Reproduce**
1. Activate an atsign
2. Open the onboarding widget and enter the atsign 
3. When the verification code screen displayed, there is no way to leave unless you enter the code to proceed.

**Expected behavior**
It would be good if we had a back or cancel button, somewhere on this screen, which takes us back tot he previous screen.

**Screenshots**
<img width="342" alt="Screenshot 2021-08-18 at 5 39 27 PM" src="https://user-images.githubusercontent.com/69275762/129979409-bb0ce107-9fe5-4d41-b218-f09662b51e59.png">

**Smartphone (please complete the following information):**
 - Device: Android and iOS devices
 

**Were you using an @‎application when the bug was found?**
  - atmosphere

**Comment by Rajasekhar695** [comment]
Fixed and tested, it's working fine. will release it in pub dev with new version.
Below attached recorded video. 


https://user-images.githubusercontent.com/60208690/130217651-b76bd814-cc40-477f-80c1-2f4f56cbf90e.mp4

**Comment by tinashe404** [comment]
confirmed fixed

**Comment by yahu1031** [comment]
This is the flow for the onboarding widget

1. Generate new atsign
2. Click on pair button
3. Enter your mail (has back)
4. OTP dialog (won't have back but we have the Wrong email)


1 -> 2 -> 3 
- User change mind, (s)he can go back to 2
- Still wants to go back then to 1
- Then cancel

1 -> 2 -> 3 -> 4
- User change their mind, (s)he can go back using the wrong mail to 3.
- Still wants to go back, (s)he can go back to 2
- Still wants to go back then to 1
- Then cancel
