### ISSUE TITLE
Onboarding widget - shows deleted atsigns in staging

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_widgets#165]
**Describe the bug**
When a new atsign is requested, the onboarding widget shows a list of existing atsigns. On staging, this is showing a list of old deleted atsigns which are no longer available on the website dashboard.

**To Reproduce**
1. Using onboarding widget, get a free atsign.
2. The widget prompts to pair an email and sends OTP for verification
3. On entering an OTP, the new atsign along with existing atsigns list is shown
4. This list is showing deleted atsigns.

**Expected behavior**
Current activated atsigns should be shown.

**Screenshots**
On the website dashboard:
<img width="1032" alt="Screenshot 2021-08-25 at 5 11 05 PM" src="https://user-images.githubusercontent.com/12222326/130784532-723bb14b-121a-41ff-915f-a8c6e9f0a6a6.png">

On the simulator:
![Simulator Screen Shot - iPhone 8 - 2021-08-25 at 16 54 36](https://user-images.githubusercontent.com/12222326/130784576-b1e82eb9-17d0-49b3-9440-26e09942ff99.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 simulator
 - OS: iOS14.4

**Were you using an @‎application when the bug was found?**
  - @ mosphere

**Additional context**
It is working fine on production endpoint.

**Comment by sarika01** [comment]
Also, on clicking the old deleted atsign, I got an email of purchase.

<img width="605" alt="Screenshot 2021-08-25 at 5 19 21 PM" src="https://user-images.githubusercontent.com/12222326/130785552-cb35e8ea-ad19-4405-823b-af7b42f0cc56.png">

And after this, the atsign does not show up on the website dashboard.

**Comment by athandle** [comment]
@sarika01 You are using API of dev and website of stage. Please check on same platforms

**Comment by sarika01** [comment]
@athandle What is the address of the website dashboard for dev?

**Comment by athandle** [comment]
https://my.atsign.wtf/

**Comment by sarika01** [comment]
@athandle The current onboarding widget uses this code to determine endpoint:
```static set rootDomain(String? domain) {
    _rootDomain = domain ?? 'root.atsign.org';
    if(_rootDomain == 'root.atsign.org') {
      website = 'https://atsign.com';
      apiEndPoint = 'my.atsign.com';
    } else {
      website = 'https://atsign.wtf';
      apiEndPoint = 'my.atsign.wtf';
    }
  }```

**Comment by sarika01** [comment]
How can we differentiate between dev and staging?

**Comment by athandle** [comment]
Just use dev for testing don't use staging

**Comment by sarika01** [comment]
Closing this issue with conclusion that free atsigns on staging environment are not supported from app side.
