### ISSUE TITLE
Create a new Sync Widget

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_widgets#186]
Lead: @sonle-geekyants 

**Is your feature request related to a problem? Please describe.**
Now that we use a progressive sync strategy, we should provide a widget that tracks progress and provides a UI component that provides feedback to the person using the app.

**Describe the solution you'd like**
For more details - see [this document](https://docs.google.com/document/d/1YlKBYHh4RQ8LeCeuQbHwJ0woEbNTFx_53jrT5YLC9vA/edit).

**Describe alternatives you've considered**
Otherwise, app developers need to develop this themselves.

**Comment by sarika01** [comment]
Target UI widgets are done.
Next task: 

- [ ] Add integration to get sync status
- [ ] test and publish the package.

Documentation items to be completed:
- [x] Package should be implemented with rSDK
- [x] Include an example (sample) app based on at_app skeleton
- [ ] Add example.md to explain how to run the sample app
- [x] Ensure the readme.md follows the best practice template (WIP)
- [x] Make sure and add in terms that will help get this package to the top of the search results 
- [ ] Update changelog.md with clear description of the update
- [ ] Bump the version as appropriate in pubspec.yaml for the package
- [ ] Bump the version as appropriate in pubspec.yaml for the example
- [ ] Check that the description is accurate in pubspec.yaml for the package
- [ ] As appropriate, add a documentation link to atsign.dev for the package

**Comment by sarika01** [comment]
No progress.

**Comment by sarika01** [comment]
Functionality is added. Needs review, testing and publishing.

**Comment by sarika01** [comment]
Requires documentation update and publishing.

**Comment by sarika01** [comment]
Published: at_sync_ui_flutter: ^1.0.1
