### ISSUE TITLE
Goes to QR Code even if onboard already has @sign in keychain and gets auth success

### ISSUE THREAD

**Issue by BermyToiga** [atsign-foundation/at_widgets#2]
I must be missing a step, but I call onboard in the init state and get auth success, but when I tap the button it takes me to the QR scanner. When I tested this earlier on phones that were previously signed in it skipped the QR and went to the next screen. I have changed the code to match the readme guidelines where before I had just imported the files from the example project

**Comment by sarika01** [comment]
The code logic is changed to give flexibility and control to the calling app. The app will have to handle the logic whether the scan qr screen needs to be shown or not.
When the onboard method returns existing AtSign from keychain, one may have to hide the button if the app supports only one atsign. In the case of multiple atsigns support, there would be multiple instances of atClient and the logic again needs to be handled in the Flutter app.

**Comment by BermyToiga** [comment]
Okay, this makes sense! I have gotten it so that if an @sign is pulled from keychain it bypasses the login screen and goes straight to the app. I think this is functional enough, but I'm wanting to make it so that it shows what @sign is authenticated on the sign in screen and then the user taps to enter the app, similar to @persona. I think the issue I'm having is that the screen renders before the onboard function finishes running.
![simulator_screenshot_92884486-F396-49E5-A2E5-B439803544E3](https://user-images.githubusercontent.com/24415651/100487591-de477f80-30df-11eb-8c00-8f3e4e5058c6.png)
I have a bit of code to display the currentAtSign if it's not null, and even though it successfully authenticates as @barbara, it always runs as if null. 
`TextSpan(
                      style: TextStyle(fontWeight: FontWeight.bold),
                      text: _takeVoteService.currentAtsign == null
                          ? "sign user!"
                          : _takeVoteService.currentAtsign.substring(1) + "1",
                    )`
I tried using basically the same thing but with _takeVoteService.getAtSign() to get the @sign from keychain, but I'm not able to treat it as a string since it's a Future. I'm not very familiar with how to handle Futures and asynchronous code so I think that is tripping me up too.
I've tried looking at the at_setting repo and seeing how it's done there, but it seems to use a lot of globals and things that I don't have set up for my app.

Any advice for this would be greatly appreciated!

**Comment by sarika01** [comment]
If you are using stateful widget, you can use a state variable to display the atsign. Similar to the example app.
https://github.com/atsign-foundation/at_widgets/blob/dev_env/atsign_authentication_helper/example/lib/second_screen.dart

For awaiting till the onboard completes, you can use Completer from 'dart:async' library.
Please refer: https://github.com/atsign-company/atmosphere/blob/master/lib/screens/home/home.dart

**Comment by BermyToiga** [comment]
Thank you that was very helpful!
