### ISSUE TITLE
at_chat_flutter - Messages don't display immediately on the client when sent

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_widgets#203]
**Describe the bug**
When you send a message, the message is not added to the chat screen (list of previous messages) until some form of update is triggered on that list, either by reopening the chat or receiving a message from that person (as show in video below).

**To Reproduce**
1. First I sent a message from phone 1 to phone 2 using [chit_chat](https://github.com/xavierchanth/chit_chat/tree/rsdk)
2. Then I waited for the message to show on phone 2. (The message did not show on the sender's side - phone 1)
3. And then I sent a reply from phone 2 to phone 1.
4. I waited for phone 1 to receive the message, and both messages showed up.
5. phone 2 did not have its message displayed.

**Expected behavior**
The message should be added to the chat screen when you send a message

**Screenshots**
[Video of the issue](https://user-images.githubusercontent.com/33691921/135331572-66bded2a-2f36-40e9-87e5-ac549cb88daa.mp4)  - sorry for poor audio quality

**Smartphone (please complete the following information):**
 - Device: Android emulators
 - OS: Both API 30

**Were you using an @‎application when the bug was found?**
  - chit_chat as listed in reproduction steps

**Additional context**

**Comment by sarika01** [comment]
Fixed in the new release 3.0.1

**Comment by xavierchanth** [comment]
Tested 3.0.1 and looks good
