### ISSUE TITLE
Profile display picture mismatch.

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_widgets#210]
**Describe the bug**
atsigns PDP(**Profile Display Pictures**) are not showing their own PDPs.

**To Reproduce**
1. Install arrive app
2. Login with any production atsign.
3. Create an event and select people from contacts.
4. While selecting try adding new contacts.
5. (OR) while editing the event try adding more contacts, at that time try adding new contacts.

**Expected behavior**
atsigns should show their own PDPs.

**Screenshots**
Here `minnu💙`(has wavi profile), `minnu💚`(has no wavi profile). When they chose they show their own PDPs.
![image](https://user-images.githubusercontent.com/35523357/136341529-aa507f94-e948-4937-bd04-23687f407dfe.png)

**Smartphone (please complete the following information):**
 - Device: Redmi 8
 - OS: Android 10

**Were you using an @‎application when the bug was found?**
  - arrive

**Comment by sachins-geekyants** [comment]
we have added a fix for it , please verify.

**Comment by yahu1031** [comment]
yes, It was fixed. I will be closing this issue.
