### ISSUE TITLE
Old invitees were replaced by new invitees and throws RangeError.

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_widgets#212]
**Describe the bug**
Already selected contacts were being cleared and newly selected contacts were being added(replaced) in selected contacts.

**To Reproduce**
1. Open arrive app.
2. Create an event and invite someone(**User X**, **User Y**).
3. Now edit the invite and invite another contact(**User Z**).
4. This (**User X**, **User Y**) will be replaced with **User Z**.
5. And when you click save it throws **RangeError**.

**Expected behavior**
It must add the **User Z** to the invited contacts list.

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/136346767-edad12ac-c383-4e45-a636-5698e28173d2.png)

**Smartphone (please complete the following information):**
 - Device: Redmi 8
 - OS: Android 10

**Were you using an @‎application when the bug was found?**
  - arrive

**Comment by sachins-geekyants** [comment]
@yahu1031 for the issue where previously added contacts were removed upon adding new contact is fixed.

**Comment by sachins-geekyants** [comment]
for range error we have a separate issue #215 .
Please verify and close it , If you can not re produce contact selection issue.

**Comment by yahu1031** [comment]
Yes, this issue wasn't able to reproduce. Closing this.
