### ISSUE TITLE
RangeError on removing invitees from the event invitation.

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_widgets#215]
**Describe the bug**
Removing contacts/invitees from the invited event throws RangeError and also doesn't update the UI till the next contacts from the removing contacts also deleted. More info in Additional info

**To Reproduce**
1. Log in to arrive and create an even with 4 or more contacts(4 in my case).
2. Try removing at least one from the list.

**Expected behavior**
It must remove the user/contact without any error.

**Logs**

```
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Valid value range is empty: 2

When the exception was thrown, this was the stack
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      List.removeAt (dart:core-patch/growable_array.dart:23:22)
#2      EventService.removeSelectedContact
package:at_events_flutter/services/event_services.dart:260
#3      _OverlappingContactsState.build.<anonymous closure>.<anonymous closure>
package:at_events_flutter/common_components/overlapping-contacts.dart:167
#4      _ContactListTileState.build.<anonymous closure>
package:at_events_flutter/common_components/contact_list_tile.dart:73
#5      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:193
#6      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:608
#7      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
#8      BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:267
#9      GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#10     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:444
#11     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:420
#12     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:278
#13     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#14     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#15     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#16     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#20     _invoke1 (dart:ui/hooks.dart:185:10)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
```

**Screenshots**

https://user-images.githubusercontent.com/35523357/136493575-eadae9d1-dbfd-4748-9545-ffb43f8057bf.mp4

**Smartphone (please complete the following information):**
 - Device: Redmi 8
 - OS: Android 10

**Were you using an @‎application when the bug was found?**
  - arrive

**Additional context**
This time I have 4 invitees to my event (exclude me). And when I tried removing the 3rd contact from the list, I got this issue.
And when I double click on the 3rd contact it removes the 3rd and 4th contact from the list. And if I click 3 times on the 2nd one it removes 2nd, 3rd, 4th contacts from the list. if I click 4 times on 1st contact, Then it will remove all the contact but still throws the range error. If I click 3 times on the 1st contact, It is not updating the UI also. When all are removed next to the contact(including it) then it removes/updates the UI.

**Comment by nitesh2599** [comment]
@yahu1031 Have added a fix for this, the updated code for events package is currently in https://github.com/atsign-foundation/at_widgets/tree/feat/event-edit-fix.

Can you please test this and let me know if you still face it ?

**Comment by yahu1031** [comment]
Hey @nitesh2599, Now that issue was resolved but when I want to save after the edit(removing some contacts from the invite list) I get this toast. No logs were traced regarding this. The only thing related to it in logs is 

```
I/Toast   (21084): Show toast from OpPackageName:com.atsign.arrive, PackageName:com.atsign.arrive
```

![image](https://user-images.githubusercontent.com/35523357/136805340-39ee1248-7ebe-4668-b0e6-072e61a325e9.png)

**Comment by nitesh2599** [comment]
@yahu1031 I tried to save the event after the edit, and I was able to do it. Can you please try it again.

**Comment by yahu1031** [comment]
Yes looks like this is fixed now. You can close this issue
