### ISSUE TITLE
at_chat_flutter -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#216]
Describe the solution you'd like:

Per the guidance from dart-lang/lints:

in pubspec.yaml:

-  pedantic: ^1.11.0
+  lints: ^1.0.1

-include: package:pedantic/pubspec.yaml
+include: package:lints/pubspec.yaml

**Comment by AlgyJr** [comment]
@TylerTrott I'd like to be assigned this issue!

**Comment by TylerTrott** [comment]
> @TylerTrott I'd like to be assigned this issue!

Hi there! Seems like someone else has actually beat you to it! My apologies, will close issue after approving and merging PR.

**Comment by baratanurag** [comment]
I want to work on this

**Comment by cpswan** [comment]
Thanks @baratanurag :)
