### ISSUE TITLE
at_common_flutter -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#217]
Describe the solution you'd like:

Per the guidance from dart-lang/lints:

in pubspec.yaml:

-  pedantic: ^1.11.0
+  lints: ^1.0.1

-include: package:pedantic/pubspec.yaml
+include: package:lints/pubspec.yaml

**Comment by AlgyJr** [comment]
Hi! I'd like to be assigned this issue!

**Comment by ksanty** [comment]
Welcome @Algy-Jr12

**Comment by TylerTrott** [comment]
> Hi! I'd like to be assigned this issue!

Hey @Algy-Jr12, if you look in a couple other of our repos, you should find this same issue! Feel free to pop a comment into one of those repos and I'll assign you and then you can raise a PR.
