### ISSUE TITLE
at_contacts_flutter -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#218]
Describe the solution you'd like:

Per the guidance from dart-lang/lints:

in pubspec.yaml:

-  pedantic: ^1.11.0
+  lints: ^1.0.1

-include: package:pedantic/pubspec.yaml
+include: package:lints/pubspec.yaml

**Comment by cpswan** [comment]
Closed by #225

**Comment by baratanurag** [comment]
I want to contribute

**Comment by cpswan** [comment]
Thanks @baratanurag, you're assigned. Please take a look at some of the similar recently merged PRs, as this is a Flutter repo, not plain Dart.

**Comment by cpswan** [comment]
Closed by #230
