### ISSUE TITLE
at_contacts_group_flutter -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#219]
Describe the solution you'd like:

Per the guidance from dart-lang/lints:

in pubspec.yaml:

-  pedantic: ^1.11.0
+  lints: ^1.0.1

-include: package:pedantic/pubspec.yaml
+include: package:lints/pubspec.yaml

**Comment by Perpetual-Incantation** [comment]
please assign this to me.

**Comment by cpswan** [comment]
Done. @Perpetual-Incantation please take a look at some of the recently merged PRs in this repo for examples of what's needed (as this is a Flutter project rather than plain Dart).

**Comment by cpswan** [comment]
Closed by #229
