### ISSUE TITLE
at_events_flutter -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#220]
Describe the solution you'd like:

Per the guidance from dart-lang/lints:

in pubspec.yaml:

-  pedantic: ^1.11.0
+  lints: ^1.0.1

-include: package:pedantic/pubspec.yaml
+include: package:lints/pubspec.yaml

**Comment by AnirbanBall** [comment]
I want to contribute

**Comment by cpswan** [comment]
Thanks @AnirbanBall you're assigned.

@yahu1031 can you please offer your usual guidance on correct form for Flutter lints (or point @AnirbanBall at some of the similar PRs that have already been approved an merged).
