### ISSUE TITLE
at_invitation_flutter -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#221]
Describe the solution you'd like:

Per the guidance from dart-lang/lints:

in pubspec.yaml:

-  pedantic: ^1.11.0
+  lints: ^1.0.1

-include: package:pedantic/pubspec.yaml
+include: package:lints/pubspec.yaml

**Comment by lkmandy** [comment]
Good day, I will like to work on this issue.
