### ISSUE TITLE
at_location_flutter -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#222]
Describe the solution you'd like:

Per the guidance from dart-lang/lints:

in pubspec.yaml:

-  pedantic: ^1.11.0
+  lints: ^1.0.1

-include: package:pedantic/pubspec.yaml
+include: package:lints/pubspec.yaml

**Comment by lkmandy** [comment]
I will like to work on this issue.

**Comment by ksanty** [comment]
Great!  You're on the issue now @lkmandy.  :)
