### ISSUE TITLE
atsign_authentication_helper  -- Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#223]
Describe the solution you'd like:

Per the guidance from [dart-lang/lints](https://github.com/dart-lang/lints#migrating-from-packagepedantic):

in ```analysis_options.yaml```:

```diff
-include: package:pedantic/analysis_options.yaml
+include: package:lints/recommended.yaml
```

**Comment by dNhunter3107** [comment]
I would like to contribute

**Comment by TylerTrott** [comment]
> I would like to contribute

Awesome! I will assign this issue to you
