### ISSUE TITLE
ReadMe.md -- Add current build/workflow status with badge

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#231]
A status badge shows whether a workflow is currently failing or passing.

A common place to add a status badge is in the ```README.md``` at the top alongside the GitHub License.

```diff
+ ![example workflow](https://github.com/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg)
```

**Comment by ArunPrasath5315** [comment]
may i work on this

**Comment by TylerTrott** [comment]
> may i work on this

Of course, will assign you.

**Comment by baratanurag** [comment]
I want to contribute on this

**Comment by baratanurag** [comment]
Can I work on this @TylerTrott  , this is issue is open from last 6 days ...... I will complete it asap :)

**Comment by cpswan** [comment]
This repo doesn't (yet) have appropriate CI tests to need a badge.
