### ISSUE TITLE
@ sign activation via OTP not working consistently

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#236]
**Describe the bug**
When activating an @ sign using the onboarding widget on @ wavi, the OTP is not working consistently. Sometimes it arrives in a few seconds, sometimes it takes over 2 minutes to arrive, sometimes it doesn't arrive at all. 

**To Reproduce**
1. Get a new @ sign
2. Click activate in the dashboard
3. When the QR code appears, enter the @ sign in the onboarding screen using @ wavi
4. The OTP will be sent via email

**Expected behavior**
The OTP comes within a few seconds

**Smartphone (please complete the following information):**
 - This was seen on both iOS and Android devices

**Were you using an @‎application when the bug was found?**
  - @wavi

**Comment by yahu1031** [comment]
Is this similar to #241?

**Comment by tinashe404** [comment]
@yahu1031 no this is not the same as 241. In this scenario the email that contains the OTP does not always arrive within a few seconds. Sometimes it takes minutes and sometimes the email does not arrive at all.

**Comment by yahu1031** [comment]
@tinashe404 Yes same with my case too...

**Comment by tinashe404** [comment]
@yahu1031 So when can we expect a fix for this?

**Comment by yahu1031** [comment]
@tinashe404 can you please check this issue and update it. If this can be closed then #241 also can be closed.

**Comment by tinashe404** [comment]
@yahu1031 I just attempted to activate @ sweetstonermetal and then pair it using the wavi app. Once the QR code was ready in atsign dashboard I entered the atsign into the onboarding widget at around 2:33pm Atlantic Time. It is now 2:38pm Atlantic Time and I still have not received the OTP.  This issue is still not resolved

**Comment by yahu1031** [comment]
@tinashe404 So this is from the production app end or are you debugging it?

**Comment by tinashe404** [comment]
@yahu1031 This is the wavi app in testflight.

**Comment by yahu1031** [comment]
Cool then need a fix 🔧

**Comment by athandle** [comment]
@yahu1031 can you please debug if API is throwing error when user is not receiving OTP?
Delay we can accept in some cases but if Email is not going then it can be a bug we need to figure out the use case, ping me we can check together.

**Comment by tinashe404** [comment]
any update on this?

**Comment by athandle** [comment]
@yahu1031 waiting for your help

**Comment by yahu1031** [comment]
I will test and update it @tinashe404 @athandle

**Comment by yahu1031** [comment]
I and @purnimavenkatasubbu tested this issue too. It wasn't reproducible.

**Comment by yahu1031** [comment]
open this issue, if it isn't solved.

**Comment by tinashe404** [comment]
I have just done the following:
- Went into the atsign.com dashboard and clicked activate on ```@doublescolorful```
- Waited for the QR code to be generated
- Opened the wavi app on my phone (testflight version)
- Entered ```@doublescolorful``` into the atsign text field
- Waited for OTP to arrive... It has been 4 minutes and the code still has not arrived to my hotmail account (checked all folders)

Are you running your tests on an emulator or on actual devices?

**Comment by yahu1031** [comment]
I tried on emulator

**Comment by tinashe404** [comment]
@yahu1031 I'll try on the simulator and see if I can get you logs

**Comment by yahu1031** [comment]
@tinashe404 I will check that from the code side. And are you sure about this is a bug and not a blocker?

**Comment by yahu1031** [comment]
@tinashe404 Made some code changes in the onboarding widget, and now it is in testing. if that works, you can expect a fix soon.

**Comment by athandle** [comment]
@tinashe404 @yahu1031 noticed 1 small thing, if you are not adding API key in app then also OTP will not go

**Comment by yahu1031** [comment]
I will check that too. Thanks for the report.

**Comment by yahu1031** [comment]
@tinashe404 Is this issue happening with release versions too(not test-flights)?

**Comment by tinashe404** [comment]
@yahu1031 I tested using the app store version of wavi and the issue was happening there too

**Comment by yahu1031** [comment]
Wait didn't I push a fix for this? Okie lemme check it and link this issue there.

**Comment by yahu1031** [comment]
PR was raised very long back - #296

**Comment by yahu1031** [comment]
Fixed and published in [at_onboarding_flutter - 3.1.3](https://pub.dev/packages/at_onboarding_flutter)

**Comment by yahu1031** [comment]
@tinashe404 I will ask the app devs to look into the code and update to the latest version. And In case this bug continues, please open it again.

\- Thank you

**Comment by tinashe404** [comment]
@yahu1031 Sounds good, thanks Minnu!
