### ISSUE TITLE
WIDGET at_onboarding_flutter to cover Windows & Linux

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_widgets#239]
We need Windows coverage for @ mosphere Pro and whilst we have the code open cover Linux

**Comment by sarika01** [comment]
The code at https://github.com/atsign-foundation/at_widgets/tree/desktop/development supports windows. Need to extend support for Linux and address issues with QR scanner and free atsign generation.

**Comment by sarika01** [comment]
• Enabled Linux and windows platform support.
• Added additional package to save backup keys.
• Added QR code file reading support for desktop platforms.

Latest code available at https://github.com/atsign-foundation/at_widgets/tree/desktop/development

**Comment by ksanty** [comment]
From meeting notes: Linux platform is enabled and code is available at https://github.com/atsign-foundation/at_widgets/tree/desktop/development
Still requires code refactoring.

**Comment by sarika01** [comment]
Packages with changes for desktop development:

- [x] at_backupkey_flutter
- [x] at_common_flutter
- [x] at_contacts_flutter
- [x] at_contact_groups_flutter
- [x] at_onboarding_flutter

In the current sprint PR25,
• Merged and published at_client_mobile for desktop support
• Checked and Merged the code from desktop/development branch
• Enabled macos, windows and linux platforms for each package. This would help to update the examples
• Updated code available on https://github.com/atsign-foundation/at_widgets/tree/add-platforms

Pending tasks:
Test each package individually and release.

**Comment by sarika01** [comment]
Packages with desktop support published to pub.dev
• at_backupkey_flutter: ^3.1.0
• at_common_flutter: ^2.0.3
• at_contacts_flutter: ^3.1.0
• at_contacts_group_flutter: ^3.1.0
• at_onboarding_flutter: ^3.1.0

@cconstab Can we close this?

**Comment by cconstab** [comment]
I do not think so as we still have bugs/features missing not tested... See todays finding..

**Comment by sarika01** [comment]
I am removing the blocker as fixes for platform support are in place(#288). 
@cconstab Please suggest if any more improvements/fixes are required.

**Comment by gkc** [comment]
This was last updated 14 months ago. I believe the onboarding widget now works for Windows and Linux. @cconstab can you confirm please, and close this issue if so?

**Comment by cconstab** [comment]
It did work but is broken again

**Comment by sonle-geekyants** [comment]
I've fixed this error build on Windows.
Branch: feature/build-desktop-app
Could you please checkout to that branch + upgrade flutter to 3.3.10 and check it? @cconstab

**Comment by cconstab** [comment]
Will do Thanks!

**Comment by sachins-geekyants** [comment]
@cconstab Is this issue resolved?

**Comment by sachins-geekyants** [comment]
Fix released with `at_onboarding_flutter 6.0.2 `

**Comment by sachins-geekyants** [comment]
@cconstab can we close this ticket?

**Comment by ksanty** [comment]
@sonle-geekyants please test in Linux TY!

**Comment by sonle-geekyants** [comment]
I've tested it on Linux and it's working well as expected. @ksanty @sachins-geekyants
