### ISSUE TITLE
argument type mismatch for qr reader in at_onboarding_flutter

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_widgets#24]
while compiling , I am getting error in at_onboarding_flutter

![Screenshot 2021-04-14 at 2 40 11 PM](https://user-images.githubusercontent.com/74917871/114686392-5b426100-9d30-11eb-9046-5e2ee51eac18.png)

**Comment by sachins-geekyants** [comment]
this is my flutter version 

![Screenshot 2021-04-14 at 2 49 00 PM](https://user-images.githubusercontent.com/74917871/114686636-9e043900-9d30-11eb-9963-994431d21b18.png)

**Comment by Sameeraja-Bharathula** [comment]
Currently at_onboarding_flutter doesn't support null-safety versions and this is causing the issue.

**Comment by murali-shris** [comment]
@sachins-geekyants can this issue be closed?

**Comment by sachins-geekyants** [comment]
@murali-shris It's fixed.
