### ISSUE TITLE
decide whether or not to add "packages" subdirectory for packages published to pub.dev

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_widgets#269]
**Is your feature request related to a problem? Please describe.**
The current directory structure creates bad links on pub.dev for Example content for flutter packages.
For example, clicking on the [example/lib/main.dart](https://github.com/atsign-foundation/at_libraries/blob/master/example/at_server_status_example.dart) link on the [at_server_status](https://pub.dev/packages/at_chat_flutter/example) Example tab returns a 404 response because it references the root of the at_libraries repo and not that of the package itself.

**Describe the solution you'd like**
Rumor has it that adding a "packages" subdirectory from the root of the repo resolves this for pub.dev. We need to test and validate this is true and then add the subdirectory if it works.

**Describe alternatives you've considered**
The other option would be to create separate repos for each package that we want to publish to pub.dev

**Additional context**

**Comment by xavierchanth** [comment]
Found a couple of tools that do this:
- https://pub.dev/packages/melos
- https://pub.dev/packages/mono_repo

Melos uses the packages directory, but mono_repo has their own custom `mono_repo.yaml` and `mono_pkg.yaml` config files.

There seems to be a good set of devs using both, but mono_repo is preferred by the dart team.

**Comment by cpswan** [comment]
Looking at Melos is already in the backlog with https://github.com/atsign-foundation/at_server/issues/374 since I came across it at DroidCon.

**Comment by xavierchanth** [comment]
Based on the needs of [atsign-foundation/at_server#374](https://github.com/atsign-foundation/at_server/issues/374), the only relevant package that I could find was melos.

I couldn't find any information for  mono_repo that discusses how they handle dependency overrides. My assumption is that they don't.

I also found [multipack](https://pub.dev/packages/multipack), this supports dependency overrides, but it modifies the pubspec.yaml, whereas it appears that melos does not.

**Comment by cpswan** [comment]
After further discussion with @XavierChanth and others I'm not sure that we should refactor existing packages. We just need to ensure that we have correct `repository:` tags defined in pubspec.yaml to prevent 404s.
