### ISSUE TITLE
Add app skeleton templates for packages in pub.dev that create working app skeletons for the app facing packages

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_widgets#270]
Lead: @XavierChanth (please update if labeled incorrectly)

**Is your feature request related to a problem? Please describe.**
For pub.dev.  content, we need a means for a developer to quickly and easily test our packages to see if they meet their needs. 

**Describe the solution you'd like**
The easiest way to do this is to extend flutter create with at_app and include our templates
For example:
```at_app create --list-samples```
```at_app create --sample=<sample ID>```

**Describe alternatives you've considered**
none

**Additional context**
This is just capturing the idea that came from @XavierChanth

**Comment by cconstab** [comment]
Added snackbar and snackbar_sender to the at_app and worked with @XavierChanth to test. More work to be done but stage 1 completed thanks to Xavier!

```
PS C:\Users\colin\GitHub\@foundation\at_app> dart run at_app/bin/at_app.dart create --list-demos

DEMO           | DESCRIPTION
---------------|-------------------------------------------------------
snackbarsender | Send snackbars to a flutter web application publically
snackbar       | Send and receive end to end encrypted snackbars
PS C:\Users\colin\GitHub\@foundation\at_app>
```

**Comment by xavierchanth** [comment]
Currently working on integrating [mason](https://pub.dev/packages/mason) to increase performance and simplify testing.

**Comment by xavierchanth** [comment]
Once my work on [at_app#42](https://github.com/atsign-foundation/at_app/issues/42) is complete, the process should be much easier, so I've dropped to 3 SP.

**Comment by xavierchanth** [comment]
Pending the merge of atsign-foundation/at_app#66 & atsign-foundation/at_app#67, this will be ready to work on.

**Comment by xavierchanth** [comment]
See also [at_app#69](https://github.com/atsign-foundation/at_app/issues/69)

**Comment by xavierchanth** [comment]
In PR 30 will take a pause on this issue, but giving it 2SP to finish manual testing on the PRs that are currently open.

**Comment by xavierchanth** [comment]
> In PR 30 will take a pause on this issue, but giving it 2SP to finish manual testing on the PRs that are currently open.

Nevermind this, I've decided to include the PR as a sprint item.
