### ISSUE TITLE
Pub.dev documentation at_follows_flutter 

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#283]
Lead: @yahu1031 
Review ticket #342 

### Pub.dev content and (source)s - CHECKLIST OF TO DO's BELOW
All the content shown on pub.dev and where it comes from. 
Example: [Shelf](https://pub.dev/packages/shelf) (will point to one of our own once completed)

- Package name, version <pubspec.yaml>
- Published date (generated)
- Platform support (generated based on project structure)
- Tabbed navigation
  - Readme (note: initial content comes from readme.md) <github repo>
  - Changelog <github repo> example: [firebase_auth](https://pub.dev/packages/firebase_auth/changelog)
  - Example (github repo)
  - Installing (generated)
  - Versions (generated) <pubspec.yaml>
  - Scores (generated)
  - **Admin  (generated)
  - **Activity log (generated)

- Right column
  - Scores  (generated)
  - Publisher  (generated)
  - Metadata  <pubspec.yaml description>
  - Homepage <pubspec.yaml>
  - Repository (generated)
  - View/report issues (generated)
  - Documentation (generated)
    - Documentation url <pubspec.yaml>
    - API reference <generated>
  - License (github repo)
  - Dependencies (generated)
  - More (generated)

### All items to be completed:
- [x] Package should be implemented with rSDK
- [x] Include an example (sample) app based on at_app skeleton
- [x] Add example.md to explain how to run the sample app
- [x] Ensure the readme.md follows the best practice template (WIP)
- [x] Make sure and add in terms that will help get this package to the top of the search results 
- [x] Update changelog.md with clear description of the update
- [x] Bump the version as appropriate in pubspec.yaml for the package
- [x] Bump the version as appropriate in pubspec.yaml for the example
- [x] Check that the description is accurate in pubspec.yaml for the package
- [x] As appropriate, add a documentation link to atsign.dev for the package

**Comment by CynthiaPeter** [comment]
I am currently working on this documentation.

**Comment by yahu1031** [comment]
About to make a release, and I cross-checked everything and the example doesn't work for some reason. Need to check it.

**Comment by sarika01** [comment]
No progress.
@srieteja Can you please look into the failing example?

**Comment by yahu1031** [comment]
This can be re-estimated to 1SP

**Comment by yahu1031** [comment]
I have created a new for example app #357. Closing this WRT to it as the documentation part was completed for this package.

**Comment by sarika01** [comment]
Moving it out till it is published. For that https://github.com/atsign-foundation/at_widgets/issues/357 needs to be completed.

**Comment by yahu1031** [comment]
The blocking tickets has been closed and we are good to go. Fix #385
