### ISSUE TITLE
I'm getting a failure to compile when trying to use an android emulator and it seems to be authentication helper related

### ISSUE THREAD

**Issue by BermyToiga** [atsign-foundation/at_widgets#3]
This is the error I'm getting:

Launching lib/main.dart on sdk gphone x86 arm in debug mode...
/Users/zara/devel/GitHub/TakeAVote/takeavote/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 24 declared in library [:atsign_authentication_helper] /Users/zara/devel/GitHub/TakeAVote/takeavote/build/atsign_authentication_helper/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.example.atsign_authentication_helper" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 24 declared in library [:atsign_authentication_helper] /Users/zara/devel/GitHub/TakeAVote/takeavote/build/atsign_authentication_helper/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 24,
  		or use tools:overrideLibrary="com.example.atsign_authentication_helper" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by sarika01** [comment]
The minimum android version supported is 24.
https://github.com/atsign-foundation/at_widgets/tree/dev_env/atsign_authentication_helper#android
The error is thrown because the minimum android version in your project is less than 24.

**Comment by BermyToiga** [comment]
Yeah, I noticed this in the error message so I added the line `<uses-sdk android:minSdkVersion="24"/>` to my /app/debug manifest but I'm still getting a similar error

**Comment by BermyToiga** [comment]
Ah, I searched the project for minSdkVersion and found the one I needed to change in build.gradle. Now I'm getting this error now though:


FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'atsign_authentication_helper'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin atsign_authentication_helper could not be built due to the issue above.

**Comment by sarika01** [comment]
Can you please try to change the current version of gradle in ../app/gradle/wrapper/gradle-wrapper.properties
from
distributionUrl=https\://services.gradle.org/distributions/[your_current_version_of_gradle].zip
to
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by BermyToiga** [comment]
Okay, I have changed this but still getting that same error

**Comment by BermyToiga** [comment]
Hi, just wanted to bring this to attention again as I'm still getting this error

**Comment by sarika01** [comment]
I am listing the three changes which rectified the issue for me:
1. In android/build.gradle
dependencies {
   classpath 'com.android.tools.build:gradle:3.6.3'
}

2. In android/gradle.properties
android.enableR8=true

3. android/gradle/wrapper/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

Maybe you can compare these files in your project to see if the change helps.

**Comment by BermyToiga** [comment]
Ah, that did it. Thank you! 
I think it was step 1 here that I had to upgrade

**Comment by BermyToiga** [comment]
Hello again, I haven't been using android since the last time that I brought this issue up, Now that I'm trying to release a version for testing I need to build to android, and I'm having failure with this same error message again:

Building plugin atsign_authentication_helper...

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'atsign_authentication_helper'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 957ms

Exception: The plugin atsign_authentication_helper could not be built due to the issue above.

**Comment by BermyToiga** [comment]
I have ran through the previous fixes and and compared those parts of the files with the example app to make sure they are the same, but still seeing this problem unfortunately

**Comment by sarika01** [comment]
Changing the references to higher version might help.
i.e.
classpath from com.android.tools.build:gradle:3.5.0   to com.android.tools.build:gradle:4.0.1
and
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip  to distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

After this, I also got this error:
Execution failed for task ':app:lintVitalRelease'

For this, in android/app/build.gradle, I changed
lintOptions {
        disable 'InvalidPackage'
}
to
lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
}

**Comment by sarika01** [comment]
The atsign_authentication_helper package is deprecated with a direction for users to use at_onboarding_flutter package instead.
