### ISSUE TITLE
Offer option to upload key file in onboarding widget

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_widgets#321]
Lead: @sarika01 

**Describe the solution you'd like**

Onboarding should offer these options:

1. Upload and existing atKeys file
2. Create a free atsign
3. Activate an atsign

For 3 it should then offer:

a.  Scan a QR code
b.  Enter the atsign name to be activated.

**Describe alternatives you've considered**
This was discussed in the architecture call, and no alternatives emerged.

**Additional context**
Asking people to enter the name of their atsign before uploading an atKeys file is error prone and inconvenient.

**Comment by sarika01** [comment]
No Progress.

**Comment by sarika01** [comment]
With the existing issues coming up in onboarding flow - https://github.com/atsign-foundation/at_widgets/issues/353, https://github.com/atsign-company/at_handle_registrar_web/issues/271
this was not taken up.

Also, similar ticket: https://github.com/atsign-foundation/at_widgets/issues/352

**Comment by sarika01** [comment]
This task is going to be addressed along with refactoring the entire code (https://github.com/atsign-foundation/at_client_sdk/issues/1615).
This will take longer than 5SPs.

**Comment by sarika01** [comment]
Adding it to current sprint with one week's effort. Need to re-evaluate post that.

**Comment by sarika01** [comment]
Work is in progress. Moving to next sprint.

**Comment by sarika01** [comment]
Planned work for first review is done and given for testing.

**Comment by sarika01** [comment]
Work is done. Planning to roll out in phased manner after other changes like chunk based encryption.

**Comment by sonle-geekyants** [comment]
I've made screenshots of the onboarding flow in Wavi app. Please check it!

**Comment by sonle-geekyants** [comment]
[screenshot.zip](https://github.com/atsign-foundation/at_widgets/files/8636829/screenshot.zip)
Please try again with this file. Thank you!

**Comment by sonle-geekyants** [comment]
@tinashe404 & @pavithragk please test this issue with two app:
- Wavi on branch: `feature/onboarding-2.0`
- Atmosphere Pro on branch: `feature/onboarding-2.0`
Both of them use the at_onboarding_flutter in branch `feature/on-boarding-2.0`

**Comment by tinashe404** [comment]
linked to issues reported on this ticket https://github.com/atsign-foundation/apps/issues/468

**Comment by gkc** [comment]
Closing as completed
