### ISSUE TITLE
Contacts widget - Make the + and x icons more noticeably different

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#334]
Lead: @sachins-geekyants 

**Is your feature request related to a problem? Please describe.**
When selecting contacts in the contacts widget you use a + icon and when deselecting you use the x icon. Currently, both icons are small and grey and don't look very different from each other especially when dealing with a long list.

**Describe the solution you'd like**
Could we possibly look into maybe adding color to these icons, using bolder icons or using words like select and deselect?

**Comment by sarika01** [comment]
No progress

**Comment by Gayathri-GA** [comment]
@tinashe404 
I have tried out these differentiations, We shall proceed further with your preference.


<img src="https://user-images.githubusercontent.com/60135944/168756035-eb295d07-9062-40b3-a4e9-8ddb12391613.png" width="300"/> <img src="https://user-images.githubusercontent.com/60135944/168756047-649a5ae4-f5bd-4216-a3bb-b45783308eec.png" width="300"/>

 <img src="https://user-images.githubusercontent.com/60135944/168756051-c8df2139-bede-4dd1-8dd4-8517719ffd8f.png" width="300"/>

**Comment by tinashe404** [comment]
@Gayathri-GA Please go with the second screenshot.. The one where the x is in a red circle. It will be easier for people who are colorblind to be able to differentiate between the icons.

**Comment by Gayathri-GA** [comment]
@tinashe404 
Fixed and raised [PR](https://github.com/atsign-foundation/at_widgets/pull/417) for approval.

**Comment by sachins-geekyants** [comment]
requires deployment and testing.

**Comment by tinashe404** [comment]
done
