### ISSUE TITLE
Pub.Dev - at_onboarding_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#345]
Under the [scores tab](https://pub.dev/packages/at_onboarding_flutter/score) it looks like null safe is not working.  Please check if something is broken or if this truly the case.  TY

![image](https://user-images.githubusercontent.com/74563278/151473103-19c2803c-21b3-4e83-a3a8-46b48c342f73.png)

**Comment by Intiserahmed** [comment]
This package depends on hive-flutter in which Flutter seems to [block dart:indexed_db  ](https://github.com/dart-lang/pana/issues/891) thats why we don't have the null safety 20 points.

**Comment by ksanty** [comment]
Should we remove at_onboarding_flutter under badges? Not consistent with other packages landing pages.

- [ ] Change Introduction to Overview? @nickelskevin 

![image](https://user-images.githubusercontent.com/74563278/151486082-d0348739-5340-4291-8e0f-aa58dcbd4b9f.png)


No use of at_backupkey_flutter under badging.
![image](https://user-images.githubusercontent.com/74563278/151486195-064e884f-c4a4-4970-bb99-654443c95e75.png)

**Comment by ksanty** [comment]
> This package depends on hive-flutter in which Flutter seems to [block dart:indexed_db ](https://github.com/dart-lang/pana/issues/891) thats why we don't have the null safety 20 points.

Thanks @Intiserahmed

**Comment by sarika01** [comment]
The null safety points can not be claimed without support from hive_flutter package. This can be taken up in future when either we move away from hive or the package supports null safety.
