### ISSUE TITLE
Pub.Dev - at_backupkey_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#346]
Under the [scores tab](https://pub.dev/packages/at_backupkey_flutter/score) it looks like null safe is not working. Please check if something is broken or if this truly the case. TY

![image](https://user-images.githubusercontent.com/74563278/151476452-a47efd3c-9106-4669-95ea-8c47f12c8d20.png)

**Comment by sarika01** [comment]
The null safety points can not be claimed without support from hive_flutter package. This can be taken up in future when either we move away from hive or the package supports null safety.
