### ISSUE TITLE
Pub.Dev - at_contacts_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#347]
Lead: @Gayathri-GA 

Inconsistency with overview section from other landing pages.  See screenshots below.

- [x] Should we use at_contacts_flutter title (inconsistent across other packages too)
- [x] No overview (see 2nd screen shot)

![image](https://user-images.githubusercontent.com/74563278/151485420-82a6217d-7660-46ad-ac68-32f17ee8014c.png)

Ideal version from at_common_flutter
![image](https://user-images.githubusercontent.com/74563278/151485433-3cc178f8-0b51-43c5-a78c-526e65e776d2.png)

**Comment by sarika01** [comment]
This is done and merged to trunk branch.
Needs to be published.

**Comment by sarika01** [comment]
The publishing was held off as there were two issues for contacts and contacts_groups.
1. Adding a contact with image was failing
2. Creating a new contacts' group was failing

This has been fixed now and would be tested and published.

**Comment by sarika01** [comment]
Published: at_contacts_flutter: ^4.0.1
