### ISSUE TITLE
Onboarding Widget - Changes to the @sign activation process

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#352]
**Is your feature request related to a problem? Please describe.**
Currently, people are required to enter the atsign dashboard, click activate on an atsign and then continue the process on their mobile device. This feels like too many steps.

**Describe the solution you'd like**
Could we make the following changes?

**Person has an atsign that they have not activated yet and they are not currently in the dashboard** 
This would no longer require them to first go to the dashboard and click activate in order to generate a QR Code
- They open the onboarding widget and type in the atsign
- They are then sent an OTP which they enter into the onboarding widget
- They are then prompted to save their key

**Person has an atsign that they have not activate yet but they are currently in the dashboard**
If they are on a mobile device
- They click activate 
- The dashboard shows them a list of apps to choose from
- If they select an app that they have already downloaded, the onboarding widget is opened with their atsign pre-populated in the text field (deep link). They just click submit, get their OTP and save their key
- If they select an app that they haven't already downloaded, they are taken to the landing page with links to the stores for download. Once downloaded, they will enter their atsign, click submit, get their OTP and save their key

If they are on desktop
- They click activate
- The dashboard shows them a list of apps to choose from and prompts them to download one onto their mobile device, along with instructions to enter the atsign, OTP and save their key

**Considerations for dess**
QR Codes will no longer be generated the way it was before in the dashboard. We will temporarily add text telling people to go to  "manage" their atsign if they are dess users and the QR code will be displayed here. 

We will also keep the 'Scan QR Code button' in the onboarding widget for now. Could we however change the text in the onboarding widget so that instead of saying "Have a QR Code?" it says "Running dess?" and then below that we will keep the 'Scan QR Code' button.

**Additional context**
A similar ticket has been created for the registrar site

**Comment by sonle-geekyants** [comment]
I fixed for both issue: [#321](https://github.com/atsign-foundation/at_widgets/issues/321) and [#352](https://github.com/atsign-foundation/at_widgets/issues/352)
Please confirm the new UI in folder `new_ip_light` and then we can merge and test.

**Comment by sonle-geekyants** [comment]
@tinashe404 & @pavithragk please test this issue with two app:
- Wavi on branch: `feature/onboarding-2.0`
- Atmosphere Pro on branch: `feature/onboarding-2.0`
Both of them use the at_onboarding_flutter in branch `feature/on-boarding-2.0`

**Comment by tinashe404** [comment]
linked to issues reported on this ticket https://github.com/atsign-foundation/apps/issues/468

**Comment by ksanty** [comment]
@tinashe404 moving to high priority so we can resolve and hopefully close in PR43

**Comment by tinashe404** [comment]
@ksanty this is bring addressed in the other ticket

**Comment by sonle-geekyants** [comment]
@tinashe404 this ticket is resolved.
Please test it with AtmospherePro in `trunk` branch.

**Comment by tinashe404** [comment]
@sonle-geekyants will do

**Comment by tinashe404** [comment]
This is done
