### ISSUE TITLE
Onboarding Widget - QR Code scanner not working

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#353]
Lead: @sonle-geekyants 

**Describe the bug**
The QR Code scanner was working in atmosphere pro v 1.0.2(21) but it is no longer working in 1.0.2(22)

**To Reproduce**
1. Click activate on an atsign in the dashboard
2. Open atmosphere pro on mobile, version 1.0.2(22) in testflight and attempt to scan the QR Code
3. The QR Code screen will display a spinning icon and remain like that until you close the screen

**Smartphone (please complete the following information):**
 - Device: iphone 11

**Were you using an @‎application when the bug was found?**
  -@mospherePro Mobile 1.0.2(22)

**Comment by sarika01** [comment]
QR scanner fix is published in at_onboarding_flutter ^4.0.0

**Comment by sarika01** [comment]
@tinashe404 This can be tested in the latest wavi app.

**Comment by tinashe404** [comment]
This is now working, could we please address the fact that the camera square doesn't fit in the UI element?
![IMG_7412](https://user-images.githubusercontent.com/69275762/154980610-07f4423c-ec83-4bbc-ba7c-d3ae089ec301.PNG)

**Comment by tinashe404** [comment]
This has been resolved
