### ISSUE TITLE
Onboarding Widget - @ signs with emojis are not activating properly

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#354]
**Describe the bug**
When you try to activate an atsign that has an emoji in it, it looks as though it has successfully activated in the app but when you look in the atsign dashboard it still says "click to scan" and Colin noticed that atsigns in this state eg haqueen💙 and tinashe💙 do not have a public key. 

**To Reproduce**
1. First get an atsign with an emoji in it
2. Then activate the atsign in the dashboard
3. Open an app eg atmosphere, and type in the atsign (don't use the QR code)
4. After activating, check the atsign dashboard and it will still say click to scan
5. You will not be able to send or receive any files in atmosphere pro

**Comment by tinashe404** [comment]
tinashe💙 was moved to canary and I tried activating it again. It is still not activating correctly. Same behaviour as above

**Comment by cpswan** [comment]
@tinashe404 atsigns can't be activated in Canary right now, as @athandle hasn't added the capability to do that yet (though it's coming with https://github.com/atsign-foundation/at_server/issues/484)

If you want to test atsigns on the Canary cluster then please make sure they're activated on Hornet first, and then they can be moved.

**Comment by tinashe404** [comment]
Closing this because it's been moved over to the registrar repo for further investigation
