### ISSUE TITLE
at_onboarding_flutter | atsign fails to activate correctly

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_widgets#355]
Lead: @XavierChanth 

Over the weekend I was trying to reset and reactivate some @‎signs to use for testing with at_app.

When I tried scanning the QR code for @‎xavierchanth💙 or @‎xavierchanth🧡, the app would hang.

- I tried with both atmosphere pro and wavi on an iPhone 11 (ios 15.3) 
- These are the latest app store versions of the apps, I reinstalled both prior to trying to activate the @‎signs

Then I tried entering @‎xavierchanth💙 into the onboarding widget and was greeted with the 2fa flow, I received the email with the code and entered it. Everything appeared to be working with this flow.

However, as I tested wavi to make sure that the secondary was up and running fine, you will see that there is no wavi page for 
@‎xavierchanth💙. On the app side, @‎xavierchanth💙 appears to be onboarded and activated, but on the registrar site, the @‎sign still shows the option to scan, i.e. it was not activated successfully.

I should also note: every time I relaunch the app and it tries to onboard @‎xavierchanth💙, I'm greeted with the 2fa flow again.

**Comment by sarika01** [comment]
Related issue: https://github.com/atsign-company/at_handle_registrar_web/issues/271

**Comment by sarika01** [comment]
at_onboarding_flutter: ^4.0.0 is published. Apps need to publish new versions with this.

**Comment by xavierchanth** [comment]
> at_onboarding_flutter: ^4.0.0 is published. Apps need to publish new versions with this.

Thank you, will that close this issue?

**Comment by sarika01** [comment]
@XavierChanth Can you please confirm if your issue is resolved in the latest version of wavi released today?

**Comment by xavierchanth** [comment]
> @XavierChanth Can you please confirm if your issue is resolved in the latest version of wavi released today?

Yes, I was able to successfully publish [my wavi page](https://wavi.ng/@xavierchanth%F0%9F%92%99).

**Comment by sarika01** [comment]
Thank you
