### ISSUE TITLE
at_follows_flutter example is not working

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_widgets#357]
Lead: @nitesh2599 

**Describe the bug**
The example app was not working with the current code in trunk(non migrated code) or at_follows_flutter-docs-update branch(migrated code)

**To Reproduce**
1. Pub get the example dependencies.
2. Run the example app
3. Onboard the app.
4. Search for some atsign and follow it.
5. Now to go Connections screen(widget).
6. It says **Failed while loading, please reopen the screen again**

**Expected behavior**
Should show the followers/following list.

**Screenshots**
<img width="259" alt="Screenshot 2022-02-07 at 7 30 12 PM" src="https://user-images.githubusercontent.com/35523357/152802136-6e761b2d-d40c-4110-868e-37a2e874c53e.png">

**Smartphone (please complete the following information):**
 - Device: iPhone13(Simulator)
 - OS: iOS15.2
 
**Were you using an @‎application when the bug was found?**
  - at_follows_flutter example app

**Additional context**
- Using `persona` namespace

**Comment by sarika01** [comment]
@yahu1031 Is there any update on this?

**Comment by yahu1031** [comment]
Not yet @sarika01 Didn't touch this yet. Will check on this today.

**Comment by yahu1031** [comment]
As I dive deeper I found this exception stopping the whole process of fetching the Followers or Following count `cached:public:image.wavi@armadillocoffeesilky does not exist in keystore`. Where I don't have any key or not even an image for `@armadillocoffeesilky` atSign.

- These are the keys with image regex in [`@mangotangostable`](https://wavi.ng/@mangotangostable) atsign

```console
@mangotangostable@scan image
data:["cached:public:image.wavi@76eldestllama","cached:public:image.wavi@7elaancomplicated","public:image.wavi@mangotangostable"]
```

- These are the keys with image regex in [`@armadillocoffeesilky`](https://wavi.ng/@armadillocoffeesilky) atsign
```console
@armadillocoffeesilky@scan image
data:["cached:public:image.wavi@76eldestllama","cached:public:image.wavi@amateurduma94","cached:public:image.wavi@tina_she"]
```

Looks like we manually passed the key list from [atsign.dart](https://github.com/atsign-foundation/at_widgets/blob/c9462e53a05f485be5f3de1509a7e7ec7f43581f/at_follows_flutter/lib/domain/atsign.dart). As the `image.wavi` is one of the keys that doesn't exist and still trying to get the value, the function `_getAtsignData()` was thrown to exception and function `getAtsignsList` was catching the exception and setting the `provider.status` to error, where it leads to **Failed message**.

Hence this is the investigation done today.

**Comment by yahu1031** [comment]
@sarika01 This wasn't resolved. As the root cause was mentioned above, It must be handled in from the `at_follows_flutter` package.

**Comment by yahu1031** [comment]
I can get notifications when someone follows me.
<img width="367" alt="Screenshot 2022-02-21 at 4 01 29 PM" src="https://user-images.githubusercontent.com/35523357/154937623-f83b9939-93a2-4412-a2ed-32dc5f544103.png">

See I have 2 followers.
<img width="1254" alt="Screenshot 2022-02-21 at 4 04 17 PM" src="https://user-images.githubusercontent.com/35523357/154938106-b8c025d5-d64b-4537-b604-d4872560a948.png">

But I have no images of the following atsigns
```console
@armadillocoffeesilky@scan image
data:["cached:public:image.wavi@76eldestllama","cached:public:image.wavi@amateurduma94","cached:public:image.wavi@tina_she"]
```

**Comment by srieteja** [comment]
@nitesh2599 I'm facing the "secondary server not found" error too which was blocking me from making any progress on at_follows_flutter_example. If you do find a solution to it please let me know, I'll do the same.

**Comment by nitesh2599** [comment]
@srieteja I was getting "`secondary server not found`" error while onboarding, so I replaced the `main.dart` with the `main.dart` we get from `at_app` template. 
And It solved the issue for me.
If you want to try it out, it's in [this](https://github.com/atsign-foundation/at_widgets/tree/fix/at_follows_flutter_example) branch.

**Comment by nitesh2599** [comment]
@yahu1031 I have added a `try{}catch{}` block to prevent the failure of fetching of one of the keys from stopping the entire function.

As mentioned in the `Expected behavior ` description of this ticket, I am able to get the `followers/following ` list.

![Screenshot 2022-02-23 at 5 24 07 PM](https://user-images.githubusercontent.com/74917928/155314524-29de882a-1b23-4b1b-9b27-7df9cc13165f.png)


The updated code is in [this](https://github.com/atsign-foundation/at_widgets/tree/fix/at_follows_flutter_example) branch.
Can you please try it out, and let me know if you are still facing it or not.

**Comment by yahu1031** [comment]
![simulator_screenshot_F754B35C-59D3-4971-9625-5B0059766F88](https://user-images.githubusercontent.com/35523357/155543886-cdab5782-9de3-4056-b117-1683d6b301e0.png)
[`@judicialabseiling`](https://wavi.ng/@judicialabseiling) has an image. But I can't get it. `_getAtsignData` I think that must be handled from app level (LMK if I'm wrong)

**Comment by nitesh2599** [comment]
@yahu1031 I have added a possible fix for the error where we don't get the image. It's in the same [branch](https://github.com/atsign-foundation/at_widgets/tree/fix/at_follows_flutter_example).

![Screenshot 2022-02-25 at 1 24 07 PM](https://user-images.githubusercontent.com/74917928/155676752-9fabea1a-9807-41bc-bdc8-d1927f9d1a25.png)

**Comment by yahu1031** [comment]
Are these fixes added to example? Or package?

**Comment by nitesh2599** [comment]
It's in package.

**Comment by nitesh2599** [comment]
@yahu1031 Did the fix work for you ?

**Comment by yahu1031** [comment]
Yes, it did.
