### ISSUE TITLE
onboarding - failing to complete activation on an @sign with a capital letter

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#364]
**Describe the bug**
There are some atsigns that people got before we stopped allowing them to enter capital letters into the atsign generator. While looking into something, I found that I am not able to activate `@Shava`.

**To Reproduce**
1. In the dashboard, click activate on the atsign with a capital letter in it
2. In any of the apps, enter the atsign into the onboarding widget (the widget won't allow you to enter a capital letter) and click submit
3. The app will say it's fetching the @ sign then you  will see an error message saying "Oops, that @ sign is invalid"
4. If you close this message, you will then be asked to enter your OTP
5. After you've enter it, the app will say that "hmm, that code is invalid or expired. Try again?" and then it will say Getting your @ sign ready. Please wait... and stay in this state until you close the app (I waited about 2 minutes)

**Expected behavior**
All atsigns should activate the same.

**Video**
https://user-images.githubusercontent.com/69275762/153429617-2b6eb6b1-7f2b-4064-a9f4-5cafdc8f70ee.MP4

**Were you using an @‎application when the bug was found?**
  - @mospherePro on mobile

**Comment by athandle** [comment]
@tinashe404  I took care of this at API level, please check and share your feedback

**Comment by tinashe404** [comment]
@athandle It's working on the dev environment. I'm assuming you haven't pushed it out to prod yet? `@Shava` still says it's invalid.

**Comment by athandle** [comment]
@tinashe404  deployed to prod just now

**Comment by tinashe404** [comment]
@athandle This is working as expected. `@Shava` has successfully update and is up and running. I also checked regular atsign activation and this is still working fine.
