### ISSUE TITLE
Onboarding - Can't select renamed atkeys on desktop

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#376]
**Describe the bug**
While using wavi desktop, I found that I am not able to upload keys that have been renamed. they are greyed out (as shown in the screenshot)

**To Reproduce**
1. Download your keys onto your pc/mac and then download them again so that the second copy is automatically renamed
2. Attempt to pair your atsign using wavi desktop
3. When it prompts you to upload your key, you will see that the renamed on is greyed out and can't be selected

**Expected behavior**
The file extension is still .atkeys so the file selector should still allow me to select the file

**Screenshots**
<img width="143" alt="Screenshot 2022-02-28 at 11 12 15 AM" src="https://user-images.githubusercontent.com/69275762/156028616-d171e4a7-2b22-41b0-9321-6b51d376cad2.png">

**Were you using an @‎application when the bug was found?**
  - Wavi desktop on Mac

**Comment by yahu1031** [comment]
Found the issue, is because of this [line](https://github.com/atsign-foundation/at_widgets/blob/trunk/at_onboarding_flutter/lib/screens/pair_atsign.dart#L469). As the extension is defined as `atKeys` and your extension there is `atkeys2`. They don't match. So it shows in gray color. So the suggestion would be is rename the file name, not the extension. Please make sure of it. you mean downloading keys from somewhere internet right? Then it won't name the file after the extension.

<img width="500" src="https://user-images.githubusercontent.com/35523357/157074794-27aadb8f-0545-4a25-8a6b-bbf2d5345065.png"/>

**Comment by tinashe404** [comment]
@yahu1031 I didn't rename the file myself. I saw the issue one someone else's machine and then replicated it on my end. What happened is that they had their keys on their computer but couldn't find them so they transferred them over to their laptop again and the system auto-renamed the file that way (on Mac). So when they were trying to use the new one, it wouldn't let them and they couldn't figure out why.

**Comment by yahu1031** [comment]
related [apple ticket](https://developer.apple.com/forums/thread/681317).

**Comment by sarika01** [comment]
@tinashe404 I tried duplicating the keys file to reproduce this. But, in every case the file extension does not change.
If the system renames it that way then I am getting a space between `.atKeys` and the number i.e. `.atKeys 2`. This format also works fine with the file picker.

Can you please let me know the exact steps that you could get this file extension. i.e. can you mention the device and OS version on which this happened?

**Comment by tinashe404** [comment]
@sarika01 Mine have a space too. The one in the screenshot above is `@wavi_key.atKeys 2` but it was greyed out.

I'm on Monterey v 12.0.1

**Comment by sarika01** [comment]
On mobile, we can pick any file. On desktop, we are filtering out 'atKeys' extension. In this case, the file looses it's extension. Hence, also enabling files without extension to show up in filter.

**Comment by sarika01** [comment]
Can be tested in the latest version on test-flight.

**Comment by tinashe404** [comment]
This works as expected!
