### ISSUE TITLE
Pub.Dev - at_events_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#380]
- [x] Overview missing from readme.md

![2022-03-06_20-12-44](https://user-images.githubusercontent.com/74563278/156966791-4392c4eb-01ca-4140-905e-ba4dbc5945f4.jpg)

Archetype readme.md example
![2022-03-06_20-09-25](https://user-images.githubusercontent.com/74563278/156966688-ddd0166b-3a2b-4fb6-9c7d-49abb7c91d01.jpg)

**Comment by sarika01** [comment]
Requires publishing to verify.

**Comment by nitesh2599** [comment]
Published at_events_flutter 3.1.4
