### ISSUE TITLE
Pub.Dev - at_location_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#381]
- [x] Overview missing from readme.md

![2022-03-06_20-47-51](https://user-images.githubusercontent.com/74563278/156969819-7b358408-376c-4e74-99cf-f0414638cbe3.jpg)

Archetype readme.md example
![2022-03-06_20-09-25](https://user-images.githubusercontent.com/74563278/156966688-ddd0166b-3a2b-4fb6-9c7d-49abb7c91d01.jpg)

**Comment by sarika01** [comment]
Requires publishing to verify.

**Comment by nitesh2599** [comment]
Published at_location_flutter 3.1.3
