### ISSUE TITLE
Pub.Dev - at_notify_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#382]
- [ ] Check documentation link is pointing to the correct page.  Currently pointing to [core technology homepage](https://atsign.dev/docs/functional_architecture/) instead of[ libraries page](https://atsign.dev/docs/functional_architecture/libraries/)

**Comment by sarika01** [comment]
Requires publishing to verify.

**Comment by nitesh2599** [comment]
at_notify_flutter 1.0.4 published
