### ISSUE TITLE
Pub.Dev - at_sync_ui_flutter

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#383]
- [x] Overview missing from readme.md
- [x] Also check for missing documentation link on right nav bar under documentation (not sure if there should be one there)

![2022-03-06_21-18-41](https://user-images.githubusercontent.com/74563278/156972577-d10ea0a1-b05c-4c96-9c7e-ba54228e96bc.jpg)

Archetype readme.md example
![2022-03-06_20-09-25](https://user-images.githubusercontent.com/74563278/156966688-ddd0166b-3a2b-4fb6-9c7d-49abb7c91d01.jpg)

**Comment by sarika01** [comment]
Requires publishing to verify.

**Comment by nitesh2599** [comment]
at_sync_ui_flutter 1.0.2 published.
