### ISSUE TITLE
Release at_dude_flutter  widget package

### ISSUE THREAD

**Issue by Intiserahmed** [atsign-foundation/at_widgets#396]
- [x] Turn At_dude app to at_dude widget package
- [x] Provide flexible attributes
- [x] Unit Test
- [x] Example app 
- [x] Independent State Management

**Comment by ksanty** [comment]
@Intiserahmed reassigning high priority, so when @CurtlyCritchlow is back we can work on.

**Comment by Intiserahmed** [comment]
Yeah Sure, Even I can pickup now where I left the work.

**Comment by Intiserahmed** [comment]
Started Working already just need some additional testing and litttle fixing.

**Comment by Intiserahmed** [comment]
The Onboarding widget issues got me blocked to go further.

**Comment by CurtlyCritchlow** [comment]
@Intiserahmed  I didn't experience any problem with onboarding. Did you try to reset the app or delete the app from your device and retry?

**Comment by Intiserahmed** [comment]
@CurtlyCritchlow sorry i throughly checked now and found 
 it is my wifi which was blocking it.

**Comment by gkc** [comment]
Closing as obsolete.
