### ISSUE TITLE
Extend libraries to include app namespace syntax

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#40]
- [x] at_follows_flutter
- [x] at_contact

**Comment by ksanty** [comment]
- [ ] at_contacts_flutter
- [ ] at_contacts_group_flutter
- [ ] at_location
- [ ] at_chat_flutter
- [ ] at_events_flutter
- [ ] at_follows_flutter
- [ ] at_location_flutter

**Comment by Sameeraja-Bharathula** [comment]
The latest code is in namespace migration branch and will be merge to trunk branch.
