### ISSUE TITLE
null-aware operator was used on non-null value in at_contacts_flutter and at_onboarding_flutter

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_widgets#408]
**Describe the bug**
In at_contacts_flutter and at_onboarding_flutter has null-aware issue with `WidgetsBinding.instance`.

**To Reproduce**
1. Install/Upgrade Flutter to 3.0.0
2. Upgrade all you at packages
3. Run any app.

**Expected behavior**
This Error/Warning is not expected

**Logs**
```console
Launching lib/main.dart on iPhone 13 in debug mode...
Xcode build done.                                           37.4s
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').

            WidgetsBinding.instance!.addPostFrameCallback((Duration timeStamp) {
                           ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((Duration timeStamp) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) async {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) async {
                   ^
: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) async {
                   ^

Connecting to VM Service at ws://127.0.0.1:52300/lITl4cNAfHU=/ws
flutter: FINER|2022-05-12 22:34:53.334998|at_skeleton_app|Environment failed to load from .env:
flutter: SEVERE|2022-05-12 22:34:54.114698|AtClientService|Atsign not found
flutter: INFO|2022-05-12 22:34:54.205284|QR Scan|camera status => PermissionStatus.denied
flutter: INFO|2022-05-12 22:34:54.206357|QR Scan|storage status is PermissionStatus.granted
```

![Screenshot 2022-05-12 at 10 38 48 PM](https://user-images.githubusercontent.com/35523357/168130676-e68aefc3-b3db-4cf2-abeb-a76b07394496.png)

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS15.4

**Were you using an @‎application when the bug was found?**
  - `@dude`

**Comment by yahu1031** [comment]
@sachins-geekyants I don't think this takes 8SP. This is because of the Flutter 3.0 version. `WidgetBinding.instance` is not nullable anymore. Previously it used to be nullable. Not sure, Please LMK this is not what this issue is about.

**Comment by sachins-geekyants** [comment]
Along with above mentioned `WidgetsBinding.instance` null aware issue we also have to apply lint rules in packages.

- [x] at_backupkey_flutter
- [x] at_chat_flutter
- [x] at_common_flutter
- [x] at_contacts_flutter
- [x] at_contacts_group_flutter
- [x] at_events_flutter
- [x] at_location_flutter
- [x] at_notify_flutter
- [x] at_onboarding_flutter
- [x] at_sync_ui_flutter
- [x] at_theme_flutter

**Comment by sachins-geekyants** [comment]
null aware fix and linting have been applied to packages - need to test examples and deploy.
Moving to next sprint.

**Comment by nitesh2599** [comment]
Packages testing and publishing:

- [x] at_backupkey_flutter
- [x] at_chat_flutter
- [x] at_common_flutter
- [x] at_contacts_flutter
- [x] at_contacts_group_flutter
- [x] at_events_flutter
- [x] at_location_flutter
- [x] at_notify_flutter
- [x] at_onboarding_flutter
- [x] at_sync_ui_flutter
- [x] at_theme_flutter

**Comment by nitesh2599** [comment]
@yahu1031 We have removed the bang operator and published the packages.

**Comment by yahu1031** [comment]
![image](https://user-images.githubusercontent.com/35523357/172396135-d665dbd2-eda6-4e32-a2cf-141e7adc3bb4.png)
Recently go this from one of the interns. Could you please check this? @nitesh2599

**Comment by nitesh2599** [comment]
@yahu1031 Can you ask for his flutter version ?

**Comment by yahu1031** [comment]
2.10.3

**Comment by nitesh2599** [comment]
This is a change made with respect to flutter 3.0 . 

If he wants to use any flutter 2... versions, he should use previous versions of the package.

**Comment by sachins-geekyants** [comment]
@yahu1031 Is the issue resolved? can we close this ticket?

**Comment by yahu1031** [comment]
yes, I'm closing this as it was resolved.
