### ISSUE TITLE
Need a custom SyncUI widget

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_widgets#431]
### Which at_widget package you want to add enhancement?

at_sync_ui_flutter

### On what platforms do you want to add enhancement?

Android, iOS, Windows, MacOS, Linux

### Is your feature request related to a problem?

We need a custom Sync UI widget where we can place that in some part of the screen. Not any toast or dialog.

### Describe the solution that you'd like

Create a few other widgets or expose/document the methods that can be used to create a custom sync UI widget.

**Comment by nitesh2599** [comment]
@yahu1031 I have added an `atSyncUIListener` method in `AtSyncUIService`, which can be used to listen to sync status changes, you can test this and see if it matches your requirement. 
It's implementation is also added in the example.

The code is in this branch https://github.com/atsign-foundation/at_widgets/tree/feat/custom_sync_ui.

**Comment by nitesh2599** [comment]
@yahu1031 Is the change added enough, or we need to do something more ?

**Comment by nitesh2599** [comment]
@yahu1031 I have added an `AtSyncUIOverlay.none` state to neither show the `overlay` nor the `dialog`. Also, added an example button with its usage in the example folder. 

https://github.com/atsign-foundation/at_widgets/commit/bdfb225b8fb5710ebe66cb3257d5184236ef36e8

**Comment by yahu1031** [comment]
Thanks @nitesh2599 will check and update.

**Comment by yahu1031** [comment]
@nitesh2599 I request you to check this PR I modified and added a custom sync indicator https://github.com/atsign-foundation/at_widgets/pull/442

**Comment by nitesh2599** [comment]
@yahu1031 Can you please verify, if all the changes needed are done, if yes, I can release a new version of `at_sync_ui_flutter`.

**Comment by yahu1031** [comment]
As of now yes, #445 Resolve this and we are good to go. I tested this on atBuzz. That's working pretty fine.

**Comment by sachins-geekyants** [comment]
Needs deployment of at_sync_ui_flutter, Moving to next sprint.

**Comment by nitesh2599** [comment]
Published at_sync_ui_flutter 1.0.4 version with above changes.
