### ISSUE TITLE
at_client/at_client_mobile, flutter_lints version to be updated in at_onboarding_flutter

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_widgets#432]
### Which at_widget package you find issue with?

at_onboarding_flutter

### On what platforms did you experience the issue?

Android, iOS, Windows, MacOS, Linux

### What version are you using?

at_onboarding_flutter: ^4.0.3

### What happened?

Due to the older versions of flutter_lints and at_client/at_client_flutter, We can't use the latest lints version in apps.

### Steps to reproduce

```bash
1. create a flutter/at_app project
2. Add at_client/at_client latest version and also the lints package latest version
3. Now pub get
```

### Additional info

Similar to https://github.com/atsign-foundation/at_client_sdk/issues/573

### Relevant log output

```console
[buzz] flutter pub get
Running "flutter pub get" in buzz...                            
Because no versions of at_onboarding_flutter match >4.0.3 <5.0.0 and at_onboarding_flutter 4.0.3 depends on at_client ^3.0.15, at_onboarding_flutter ^4.0.3 requires at_client ^3.0.15.
And because at_client >=3.0.4 depends on lints ^1.0.1, at_onboarding_flutter ^4.0.3 requires lints ^1.0.1.
So, because buzz depends on both at_onboarding_flutter ^4.0.3 and lints ^2.0.0, version solving failed.
pub get failed (1; So, because buzz depends on both at_onboarding_flutter ^4.0.3 and lints ^2.0.0, version solving failed.)
exit code 1
```

**Comment by Sardar1208** [comment]
- I have added a dependency override for lints 2.0.0 so it works for now. 
- Meanwhile, I have posted that the at_client will need an update for lints.
- Also, I have tested the new list rules in version 2.0.0 are working fine.

Pr - https://github.com/atsign-foundation/at_widgets/pull/438

**Comment by sachins-geekyants** [comment]
@Sardar1208 can we also upgrade lint version of other packages along with onboarding?

**Comment by sachins-geekyants** [comment]
reducing sp and moving to next sprint.

**Comment by nitesh2599** [comment]
Updated all the packages after analysing https://github.com/atsign-foundation/at_widgets/commits/flutter_lint_override, will be released after new version of at_client is released using `flutter_lints` `2.0.1`

**Comment by nitesh2599** [comment]
Needs to validate and deploy all the packages, moving to next sprint.

**Comment by sachins-geekyants** [comment]
Need to release at_onboarding_flutter-3 and update all package examples with it.
Moving to next sprint.

**Comment by nitesh2599** [comment]
Released:
- at_common_flutter (2.0.9)
- at_contacts_flutter (4.0.6)
- at_contacts_group_flutter (4.0.8)
- at_location_flutter (3.1.7)
- at_events_flutter (3.1.8
-  at_sync_ui_flutter (1.0.5)
- at_notify_flutter (1.0.6)
- at_theme_flutter (1.0.3) 

with flutter_lints 2.0.1 versions.

**Comment by sachins-geekyants** [comment]
Moving to requires validation

**Comment by gkc** [comment]
Closing as complete
