### ISSUE TITLE
OnBoarding return type

### ISSUE THREAD

**Issue by kzawadi** [atsign-foundation/at_widgets#472]
### Which at_widget package you want to add enhancement?

at_onboarding_flutter

### On what platforms do you want to add enhancement?

Android, iOS, Windows, MacOS, Linux

### Is your feature request related to a problem?

When calling authenticate() method it has a return type that is dynamic ...  This introduces some problems with some strict rules of clean dart code, It's a bit bad to return dynamic especially in this situation when I clearly want to tell my users (people) what the problem was specifically programmatically. 

### Describe the solution that you'd like

This method should return a type as other parts of it already return a concrete type in this case an enum [ResponseStatus]. And the reason for returning dynamic was just to be able to throw a string '@sign cannot be null ' So just adding an enum value representing this case would do the trick.  currently, 
the enum is `enum ResponseStatus {
                serverNotReached,
                authSuccess,
          authFailed,
  timeOut,
}`

 So adding `enum ResponseStatus {
  serverNotReached,
  authSuccess,
  authFailed,
  timeOut,
  atSignCannotbeNull 
}`

will help in handling programmatically this return value.

### Describe alternatives that you have considered

So far i have just patched it with an if statements `      if (status == '@sign cannot be null') =>
        return ResponseStatus.authFailed;
      `  
Just looking at the result named status from the package method `authenticate` which returns dynamic and if it has a string `'@sign cannot be null` then we just return a proper but not very accurate but general failure enum value of `ResponseStatus.authFailed`

### Additional context

This method's return of dynamic makes it hard a bit to handle its return values programmatically. It was hand for when the package wanted to notify a user of the error but as a developer, I want to handle this error programmatically not only showing the user but also adding some logic plus dynamics are a nuisance some lint rules we have is not having dynamics but predictable types. :::::
Another example is this method `  Future<AtStatus> get(String atSign) async {}` it return a concrete type `AtStatus` which is a joy working with it

**Comment by sachins-geekyants** [comment]
@kzawadi return type is added for `authenticate()` method, please check in trunk branch.

**Comment by kzawadi** [comment]
> @kzawadi return type is added for `authenticate()` method, please check in trunk branch.

That's great
