### ISSUE TITLE
at_onboarding_reset_screen.dart need to be imported to access AtOnboardingResetResult enum

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/at_widgets#507]
### Which at_widget package you find issue with?

at_onboarding_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

at_onboarding_flutter: 5.0.0

### What happened?

I need to `import 'package:at_onboarding_flutter/screen/at_onboarding_reset_screen.dart';` to access the `AtOnboardingResetResult` enum.

I think the `AtOnboardingResetResult` enum should be in it's own file so it can be imported as `import 'package:at_onboarding_flutter/at_onboarding_reset_result.dart';` or `import 'package:at_onboarding_flutter/at_onboarding_flutter.dart';`

### Steps to reproduce

```bash
1. import 'package:at_onboarding_flutter/at_onboarding_flutter.dart'

3. Create a variable `var a = AtOnboardingResetResult.success;` and you'll get an undefined name error.
...
```

**Comment by sachins-geekyants** [comment]
@CurtlyCritchlow Are you facing the same issue with onboarding `6.0.0` ?
