### ISSUE TITLE
Pub.Dev GitHub Repo links point to Master branch

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_widgets#53]
**Describe the bug**
Widgets that exist on pub.dev all have links that point to master branch rather than trunk.

**To Reproduce**
1. First I 'Navigate to a widget page such as https://pub.dev/packages/at_events_flutter'
2. Then I 'Navigate to the right nav bar and click Repository (GitHub)'

**Expected behavior**
Persons who click link should be navigated to trunk branch

**Comment by cpswan** [comment]
Waiting on pushes to pub.dev by @sarika01 for the changes in #44 to take effect
