### ISSUE TITLE
Not able to scroll on the reset screen in the onboarding widget

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#56]
**Describe the bug**
If a person has numerous atsigns they are not able to reset the app they are using because when you try to reset, the widget does not allow you to scroll up or down and so the person cannot access all their atsigns or the button.

**To Reproduce**
1. First I pair numerous atsigns, at least 10 (the person who reported the issue had 80 atsigns)
2. Then I try to reset an app (buzz or wavi) and the screen pops up for me to select the atsigns I would like to remove the app and proceed to reset the app
3. And the app will not allow me to scroll through the list of atsigns or access the reset button

**Expected behavior**
I expect to be able to scroll through my list of atsigns, select any or all of them and then reset the app.

**Smartphone:**
 - iOS and Android

**Were you using an @application when the bug was found?**
 - Found while using Buzz and Wavi

**Comment by DivyaYadavareddy** [comment]
It is working fine with at_onboarding_flutter v2.1.2 , below i attached recorded video of wavi.
Can you please check with this version?

https://user-images.githubusercontent.com/60208911/127463140-c8f71205-5841-43df-86c0-d27e514155e7.mp4

**Comment by XavierChanth** [comment]
I can confirm this issue is resolved on my end.
