### ISSUE TITLE
docs: at_onboarding_flutter docs insufficiently clear for new users

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_widgets#587]
### Which at_widget package you find issue with?

at_onboarding_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

Latest

### What happened?

Customer @ralfeus encountered issues using the widget because
* description of usages of the parameters to `AtOnboarding.onboard`, especially `AtOnboardingConfig`, are insufficiently `detailed
* dependencies between parameters (e.g. rootEnvironment, domain and API key) are not made sufficiently clear
* sensible default values for the parameters are not set
* incompatible config settings are not rejected

### Steps to reproduce

```bash
Use the widget with no prior knowledge
```

**Comment by ksanty** [comment]
Related issue - https://github.com/atsign-foundation/at_widgets/issues/583

**Comment by JeremyTubongbanua** [comment]
I can take this on - if no one is working on it already :) @gkc @sonle-geekyants

**Comment by sonle-geekyants** [comment]
> I can take this on - if no one is working on it already :) @gkc @sonle-geekyants

Please check it for me. Thank you very much!

**Comment by sonle-geekyants** [comment]
https://docs.google.com/document/d/1cywjdHoOp6AQHZxyu8qyc_14xMtFzRwrzn0iI5h_zZA/edit @JeremyTubongbanua this is a document, you can check and edit it.
