### ISSUE TITLE
at_backupkey_flutter not giving option to save atKey locally in android

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_widgets#609]
### Which at_widget package you find issue with?

at_backupkey_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

at_backupkey_flutter: 4.0.8

### What happened?

While saving the atKey on android devices, it does not give the option to save locally.

### Steps to reproduce

```bash
1. Onboard with an atSign and try to backup key using at_backupkey_flutter
2. There is no option to save locally.
```

**Comment by sonle-geekyants** [comment]
https://user-images.githubusercontent.com/88494375/220546803-454c9fa6-71e5-4a43-90eb-baf81ad34e3c.mov

I'm using android 9 and can still save atSign locally.

**Comment by sonle-geekyants** [comment]
I try test on android 12 also working. @sachins-geekyants

**Comment by sachins-geekyants** [comment]
With `at_backupkey_flutter 4.0.9`, we have options to either download or share the backup key in android.
