### ISSUE TITLE
Cannot generate atSign in release mode on Android  [atBuzz]

### ISSUE THREAD

**Issue by Sardar1208** [atsign-foundation/at_widgets#627]
### Which at_widget package you find issue with?

at_onboarding_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

5.0.5

### What happened?

When we try to generate a new atSign, after all the steps it says "atSign not registered" at the end. This happens before the step to save the atKey. 

### Steps to reproduce

```bash
1. Run atBuzz in release mode
2. Try generating a new atSign.
```

**Comment by gkc** [comment]
Marking this as P1 as it looks important to me

**Comment by Sardar1208** [comment]
This issue is not happening now.
(Tested on Android Play store version)
