### ISSUE TITLE
failed in processing atkey zip file Error in the onboarding widget version 2.0.0

### ISSUE THREAD

**Issue by Intiserahmed** [atsign-foundation/at_widgets#65]
**Describe the bug**

When I try to pick my atkey zip file from my android phone it gives me the error in the wavi app. I also faced the same error when I used onboarding widget 2.0.0 in  demo apps

**To Reproduce**
1. First I '...'

2. Then I '...'
3. And then '...'
4. 

**Expected behavior**

**Screenshots**
![Screenshot_20210702-104048](https://user-images.githubusercontent.com/57252940/124344722-d0b62300-dbf5-11eb-92f5-fec46652dda9.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @application when the bug was found?**
  

**Additional context**

**Comment by buzz** [comment]
> * [e.g. @buzz, @tmosphere]

Please stop mentioning me in this repo. Thank you

**Comment by ksanty** [comment]
> > * [e.g. @buzz, @tmosphere]
> 
> Please stop mentioning me in this repo. Thank you

Hi @Intiserahmed I'm going to send you a video showing you how to put a space separator between @ and buzz.

**Comment by buzz** [comment]
@ksanty Please stop mentioning my username in this repository. Thank you very much

**Comment by XavierChanth** [comment]
Same issue:

```
I/flutter ( 8361): SEVERE|2021-07-06 14:16:04.419833|QR Scan|Uploading backup zip file throws type 'Future<FilePickerResult?>' is not a subtype of type 'FutureOr<FilePickerResult>' in type cast
```
It appears to start at ```/lib/screens/pair_atsign.dart``` line 272-274

```
FilePickerResult result = await (FilePicker.platform.pickFiles(
    type: FileType.any,
    allowMultiple: true) as FutureOr<FilePickerResult>);
```

Removing the typecast and changing result's type to FilePickerResult? allows the project to build, however I'm still unable to onboard. I get sent back to the upload screen.

**Comment by sarika01** [comment]
Both ".zip" and ".atKeys" extension files seem to be working fine with at_onboarding_flutter v2.1.0
@Intiserahmed Can you please check with this version?

**Comment by Intiserahmed** [comment]
@sarika01 checked giving the future file picker error as @XavierChanth mentioned.

**Comment by XavierChanth** [comment]
Could it be from the flutter sdk version I'm using?
```yaml
#/example/pubspec.yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
```

I suppose that my issues come from using sdk 2.12 in pubspec.yaml:
```yaml
#/my_app/pubspec.yaml
environment:
  sdk: ">=2.12.0 <3.0.0"
  ```

**Comment by Intiserahmed** [comment]
@XavierChanth 2.12 is for null safety... I'm afraid 2.7 doesn't support null safety.

**Comment by XavierChanth** [comment]
I'm using 2.12, example is using 2.7, I get major issues when trying to use 2.7, since all the code is written to use null safety in the app.

**Comment by murali-shris** [comment]
> Both ".zip" and ".atKeys" extension files seem to be working fine with at_onboarding_flutter v2.1.0
> @Intiserahmed Can you please check with this version?

@Intiserahmed does the issue exist with at_onboarding_flutter v2.1.0?

**Comment by Intiserahmed** [comment]
@murali-shris Yeap It's working like a charm

**Comment by tinashe404** [comment]
Closing this on your behalf @Intiserahmed
