### ISSUE TITLE
Uplift our flutter widgets for Dart 3.0 / Flutter 3.10

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_widgets#654]
### Is your feature request related to a problem? Please describe.

Dart 3 and flutter 3.10.0 are now stable and fully released

These releases introduce a number of breaking changes e.g. around null safety, as well as having stricter lint rules resulting in lint warnings where previous there were only lint info messages

Those breaking changes can be expected to impact our dependencies as well as our own code.

### Describe the solution you'd like

1. Each package in this repo needs to be analyzed using latest stable version of flutter (>= 3.10.0) or dart for any pure dart package (>= 3.0.0)
2. Errors and lint warnings should be removed
3. If there were actual errors (e.g. because the smarter null safety checks are picking something up) then a new version of the package should be published
4. Ensure that in addition to the widget package itself, the analysis and fixing is also done on the `example` within each widget package

### Tracker
**Please update this table and assign yourself some package(s)**
| Done? | Package | Assignee |
| ----- | ------- | -------- |
| Yes | at_backupkey_flutter | @sonle-geekyants  |
| Yes| at_chat_flutter | @sonle-geekyants |
| Yes | at_common_flutter | @Xlin123  |
| Yes | at_contacts_flutter | @sachins-geekyants |
| Yes | at_contacts_group_flutter | @sonle-geekyants  |
| Yes | at_events_flutter | @Xlin123 |
| Yes | at_follows_flutter | @Xlin123 |
| Yes | at_invitation_flutter | @Xlin123|
| Yes | at_location_flutter | @sonle-geekyants |
| Yes | at_login_flutter | @Sardar1208  |
| Yes | at_notify_flutter | @Xlin123 |
| Yes | at_onboarding_flutter | @Xlin123 |
| Yes | at_sync_ui_flutter |@natt-n |
| Yes | at_theme_flutter | @Xlin123 |

**Comment by Xlin123** [comment]
Changes are on the dart-3 branch.

I put at_onboarding_flutter on it's own branch (dart-3-onboarding.)

**Comment by Xlin123** [comment]
@sonle-geekyants just a heads up, I was briefly looking at that package and it seemed that the EncryptionService.decrypt method was missing in lib/services/chat_service.dart. I did some looking and found out that it got removed in **[this](https://github.com/atsign-foundation/at_client_sdk/commit/797dcc6784c4878896feee321477dfc201cfa9a2)** commit.

**Comment by sonle-geekyants** [comment]
@murali-shris Because of [this](https://github.com/atsign-foundation/at_client_sdk/commit/797dcc6784c4878896feee321477dfc201cfa9a2) commit, some packages were missing the EncryptionService.decrypt method. Please check this issue for me.

**Comment by Xlin123** [comment]
@sonle-geekyants can you change the status of the packages that are blocked to "blocked"? I just ran into another package that was using it.

**Comment by sachins-geekyants** [comment]
@Xlin123 I have migrated the chat service and replaced the `decrypt` method.
Please check this PR : https://github.com/atsign-foundation/at_widgets/pull/666

**Comment by Xlin123** [comment]
@sachins-geekyants got it thanks!
