### ISSUE TITLE
Wrong Error message dialog when Wi-Fi is turned off

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/at_widgets#662]
### Which at_widget package you find issue with?

at_onboarding_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

6.0.3

### What happened?

If my Wi-Fi is turned off and I try to upload my backup keys file, I get an error message saying "Your atSign is not registered yet. Please try with the registered one."

My atsign is registered, if I turn my Wi-Fi back on and upload my backup keys file, my assign is successfully uploaded.

### Steps to reproduce

```bash
1. Open the onboarding widget
2. Turn off Wi-Fi'
2. Upload Backup Key file
3. Select an activated atKey
4. Error dialog will show up saying "Your atSign is not registered yet. Please try with the registered one."
...
```

### Relevant log output

```console
2
I/flutter (14910): _checkRootLocation error: Exception: Failed connecting to root server url root.atsign.org on port 64
I/flutter (29216): FINER|2023-05-22 11:58:25.015779|NetworkUtil|Unable to connect to internet
```

**Comment by sachins-geekyants** [comment]
Fix merged into trunk.
