### ISSUE TITLE
After a successful onboarding, the app remains in Generate free atsign screen

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_widgets#684]
### Which at_widget package you find issue with?

at_onboarding_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

at_onboarding_flutter : trunk

### What happened?

After a successful onboarding of a new atsign, the app still remains in the Generate a free atsign screen, Have to go to switch atsign and then select the newly created atsign

https://github.com/atsign-foundation/at_widgets/assets/43639593/6c77e184-8521-4bfa-9c67-def1f764c90f

### Steps to reproduce

```bash
1. Run atmospherePro/wavi app trunk branch of code (that has onboarding_flutter trunk branch)
2. Select Generate a new free atsign
```

**Comment by Sardar1208** [comment]
@purnimavenkatasubbu This issue is fixed in this PR - https://github.com/atsign-foundation/at_widgets/pull/699
Can you please check?

**Comment by purnimavenkatasubbu** [comment]
Verified with the above branch. The issue is fixed now.

**Comment by Sardar1208** [comment]
Thank you. Can we close this ticket?

**Comment by purnimavenkatasubbu** [comment]
yes
