### ISSUE TITLE
at_onboarding_flutter - changes and testing for at_auth and APKAM

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_widgets#750]
### Which at_widget package you want to add enhancement?

at_onboarding_flutter

### On what platforms do you want to add enhancement?

Android, iOS

### Is your feature request related to a problem?

n/a

### Describe the solution that you'd like

Continue with the changes done in apkam_changes branch.
Integrate at_auth changes if any
Testing for enrollment scenarios

**Comment by sitaram-kalluri** [comment]
After uptaking the at_auth package changes into at_client_mobile, tested the changes in using the mobile apps and all the scenarios are working fine.

Following are the scenarios tested:
- Create a new atSign and onboard the change.
- Uninstall the atSign and use atKeys and onboard the atSign
- After onboard, kill the app and launch the app again - To test the authenticate method.
- Reset the atSign and use atKeys to authenticate the app.

**Comment by sitaram-kalluri** [comment]
Spent 3-SP in PR-74

The changes related to APKAM are completed the changes are available in [at_enrollment_app](https://github.com/atsign-foundation/at_widgets/tree/at_enrollment_app)

The changes include generation of deep-link and submitting an enrollment request.

**Comment by sitaram-kalluri** [comment]
Spent 3 SP in PR-75.

- The changes in enrollment app are tested and works fine. Pending work is to test the onboarding flow with the existing apps to ensure there are no regressions and then publish at_client_mobile package and at_onboarding_flutter package.

**Comment by sitaram-kalluri** [comment]
The changes are completed the pushed to : https://github.com/atsign-foundation/at_widgets/tree/enrollment_screens branch.
Going forward the APKAM tracking with done in the following tracker ticket: https://github.com/atsign-foundation/operations/issues/88. 
Closing this git issue.
