### ISSUE TITLE
at_follows_flutter Unused import: 'package:at_utils/at_logger.dart'

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_widgets#764]
### Which at_widget package you find issue with?

at_follows_flutter

### On what platforms did you experience the issue?

Linux

### What version are you using?

3.0.10

### What happened?

```
warning • Unused import: 'package:at_utils/at_logger.dart' • example/lib/screens/follows_screen.dart:5:8 • unused_import
```

### Steps to reproduce

```bash
1. Clone this repo
2. `cd at_widgets/packages/at_follows_flutter`
3. `flutter analyze --no-fatal-infos`
```

**Comment by Sardar1208** [comment]
moving to next sprint

**Comment by Sardar1208** [comment]
needs deployment and validation. Assigning 0SP and moving to next sprint

**Comment by Sardar1208** [comment]
@cpswan the packages are deployed. Can we close this ticket ?
