### ISSUE TITLE
at_invitation_flutter The value of the field '_logger' isn't used

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_widgets#765]
### Which at_widget package you find issue with?

at_invitation_flutter

### On what platforms did you experience the issue?

Linux

### What version are you using?

2.0.1

### What happened?

```
warning • The value of the field '_logger' isn't used • example/lib/main.dart:40:22 • unused_field
```

### Steps to reproduce

```bash
1. Clone this repo
2. `cd at_widgets/packages/at_invitation_flutter`
3. `flutter analyze --no-fatal-infos`
```

**Comment by Sardar1208** [comment]
moving to next sprint

**Comment by Sardar1208** [comment]
needs deployment and validation. Assigning 0SP and moving to next sprint

**Comment by Sardar1208** [comment]
@cpswan the packages are deployed. Can we close this ticket ?
