### ISSUE TITLE
at_sync_ui_flutter dependencies

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_widgets#768]
### Which at_widget package you find issue with?

at_sync_ui_flutter

### On what platforms did you experience the issue?

Linux

### What version are you using?

1.0.9

### What happened?

```
Because at_sync_ui_flutter_example depends on at_onboarding_flutter ^6.1.3 which depends on at_sync_ui_flutter ^1.0.8, at_sync_ui_flutter from hosted is required.
So, because at_sync_ui_flutter_example depends on at_sync_ui_flutter from path, version solving failed.
```

### Steps to reproduce

```bash
1. clone this repo
2. `cd at_widgets/packages/at_sync_ui_flutter`
3. `flutter pub get`
```

**Comment by Sardar1208** [comment]
moving to next sprint

**Comment by Sardar1208** [comment]
needs deployment and validation. Assigning 0SP and moving to next sprint

**Comment by Sardar1208** [comment]
@cpswan the packages are deployed. Can we close this ticket ?
