### ISSUE TITLE
Add a Flutter widget for generic notifications

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_widgets#78]
**Is your feature request related to a problem? Please describe.**
As described in this [document](https://docs.google.com/document/d/1z8xAjqJQ3NtqYOAhhgIvQULGeF9ZL7EtwqnGSjBjiXU/edit#), there is an opportunity to provide an end-to-end encrypted, peer-to-peer, surveillance free notification service.

**Describe the solution you'd like**
The approach needs to be discussed in the architecture call.
Adding to the backlog so we can plan accordingly.

**Describe alternatives you've considered**
This could be accomplished as a widget only.

**Comment by sarika01** [comment]
Needs to be tested with rSDK and published.

**Comment by sarika01** [comment]
Needs review and publishing.

**Comment by sarika01** [comment]
Requires documentation and publishing.

**Comment by sarika01** [comment]
Package published: https://pub.dev/packages/at_notify_flutter
