### ISSUE TITLE
Use textScaler instead of textScaleFactor

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_widgets#790]
### Which at_widget package you want to add enhancement?

at_backupkey_flutter, at_common_flutter, at_contacts_flutter, at_contacts_group_flutter, at_events_flutter, at_follows_flutter, at_invitation_flutter

### On what platforms do you want to add enhancement?

Android, iOS, Windows, MacOS, Linux

### Is your feature request related to a problem?

flutter analyze returns deprecation info like:

```
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was
          deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after
          v3.12.0-2.0.pre • lib/widgets/otp_dialog.dart:41:51 • deprecated_member_use
```

### Describe the solution that you'd like

Switch to the recommended textScaler

### Describe alternatives that you have considered

NA

### Additional context

There are some other info notes on deprecation that should be dealt with, but this is the most common one.

**Comment by Sardar1208** [comment]
Needs deployment and testing. Assigning 0SP

**Comment by Sardar1208** [comment]
@cpswan all packages have been published with this fix. Can we close this ticket ?
