### ISSUE TITLE
All widgets need new versions to be published which can use at_commons ^4.0.0

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_widgets#794]
### What happened?

Apps cannot use atest versions of at_client until this is resolved. See also https://github.com/atsign-foundation/at_client_sdk/issues/1232 for at_client_mobile which also needs to be upgraded

**Comment by VJag** [comment]
@sachins-geekyants @Sardar1208 Please talk to @gkc or @VJag if you need any clarification. It a p0.

**Comment by ksanty** [comment]
Corresponding ticket https://github.com/atsign-foundation/apps/issues/780

**Comment by Sardar1208** [comment]
@VJag These packages are ready. I will start the release process now.
`at_onboarding_flutter`, `at_follows_flutter`, `at_invitation_flutter`, `at_notify_flutter`, `at_theme_flutter`

The other packages need `at_contact` to be updated to support `at_commons: 4.0.1`

**Comment by Sardar1208** [comment]
New versions of all packages are published. 
@gkc Can we close this ticket ?

**Comment by Sardar1208** [comment]
Assigning 0SP and moving to next sprint
