### ISSUE TITLE
Review for missing content - at_contacts_flutter (Scores Tab)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#83]
[Scores tab](https://pub.dev/packages/at_contacts_flutter/score) missing documentation for:

- [x] provide documentation
- [ ] support multiple platforms
- [ ] support sound null safety

**Comment by ksanty** [comment]
Hi @sachins-geekyants we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue.  Creating new issue cards today.

**Comment by sachins-geekyants** [comment]
Duplicate of [this](https://github.com/atsign-foundation/.github/issues/6) ticket.
