### ISSUE TITLE
Clear up `info` messages from `flutter analyze`

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_widgets#847]
### Which at_widget package you find issue with?

at_backupkey_flutter, at_chat_flutter, at_common_flutter, at_contacts_flutter, at_contacts_group_flutter, at_events_flutter, at_follows_flutter, at_invitation_flutter, at_notify_flutter, at_onboarding_flutter, at_sync_ui_flutter, at_theme_flutter

### On what platforms did you experience the issue?

Linux

### What version are you using?

Latest

### What happened?

In #846 we made the call to enable infos on beta channel so we get early warning of deprecation. This ticket is to clear down existing tech debt.

### Steps to reproduce

```bash
1. Go to any of the listed packages
2. Run `flutter analyze`
```

### Additional info

#842 and #843 take priority, as they're already showing issues in stable channel. This should help us avoid similar problems in the future.

### Flutter analyze output

An example:

```console
Analyzing at_backupkey_flutter...                               

   info • 'background' is deprecated and shouldn't be used. Use surface instead. This feature was deprecated after v3.18.0-0.1.pre • example/lib/main.dart:57:19 • deprecated_member_use
   info • 'background' is deprecated and shouldn't be used. Use surface instead. This feature was deprecated after v3.18.0-0.1.pre • example/lib/main.dart:66:19 • deprecated_member_use
```
```

**Comment by srieteja** [comment]
Implemented changes to clear out the issues reported by `flutter analyze`. Carrying it forward to PR88 for manually testing each of these example apps/apps.
