### ISSUE TITLE
Missing documentation - at_onboarding_flutter (Scores Tab)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#87]
[Score tab](https://pub.dev/packages/at_onboarding_flutter/score) is missing documentation for:

- [x] provide documentation
- [x] support multiple platforms 
- [x] pass static analysis
- [ ] support sound null safety

**Comment by ksanty** [comment]
Hi @sarika01 we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue. Creating new issue cards today.

**Comment by yahu1031** [comment]
I think this gonna be covered by @Intiserahmed

**Comment by yahu1031** [comment]
@Intiserahmed can you please look at [this](https://pub.dev/packages/at_onboarding_flutter/score) as #281 as this was taken up by you.

**Comment by sarika01** [comment]
This is already actioned and published under https://github.com/atsign-foundation/at_widgets/issues/281

**Comment by yahu1031** [comment]
@sarika01 But still, the score tab has 20 points less. That is due to null safety issues.

**Comment by sarika01** [comment]
@yahu1031 That is applicable to all packages depending upon hive. There is nothing much that we can do at this point.

**Comment by yahu1031** [comment]
13 packages don't show `null-safety` tag in pub.dev

**Comment by sarika01** [comment]
All packages depending upon hive_flutter will have this issue. This was brought up and discussed months back. The decision was to leave it as it is till the at_client moves away from hive.

**Comment by yahu1031** [comment]
Okie then, I'm closing this.
