### ISSUE TITLE
Review for missing content - at_onboarding_flutter (API Reference)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#88]
- [ ] Right nav bar [API documentation](https://pub.dev/documentation/at_onboarding_flutter/latest/) requires documentation review (samples and examples)
- [ ] Do we need a [documentation link](https://pub.dev/packages/at_onboarding_flutter)?

Please check libraries as well (current, samples and examples)
[LIBRARIES](https://pub.dev/documentation/at_onboarding_flutter/latest/)

- [ ] app_constants
- [ ] at_onboarding_flutter
- [ ] atsign_list_screen
- [ ] color_constants
- [ ] custom_appbar
- [ ] custom_button
- [ ] custom_dialog
- [ ] custom_nav
- [ ] custom_strings
- [ ] custom_textstyles
- [ ] freeAtsignService
- [ ] images
- [ ] onboarding_service
- [ ] onboarding_widget
- [ ] pair_atsign
- [ ] private_key_qrcode_generator
- [ ] response_status
- [ ] size_config
- [ ] strings
- [ ] web_view_screen

**Comment by ksanty** [comment]
Hi @sarika01 we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue. Creating new issue cards today.

**Comment by yahu1031** [comment]
This gonna be covered by @Intiserahmed I guess
