### ISSUE TITLE
Missing documentation - at_location_flutter (Scores Tab)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#90]
[Scores tab](https://pub.dev/packages/at_location_flutter/score) is missing documentation for 

- [ ] provide documentation
- [ ] support multiple platforms
- [ ] support sound null safety

**Comment by ksanty** [comment]
Hi @nitesh2599 we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue. Creating new issue cards today.

**Comment by nitesh2599** [comment]
at_location_flutter package is getting modified currently, will add documentation with respect to new changes, and will update details [here](https://github.com/atsign-foundation/.github/issues/11).
